# -*- coding: utf-8 -*-
"""TP Final Taller II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1ESWDNcLKQtPcKMybujkFPRr4aDo-ry

# Dataset

Comenzamos analizando la población general del dataset NTR Aarogyaseva para
comprender la estructura demográfica del conjunto de casi 480.000 registros
de pacientes cubiertos por el programa de salud pública.

El sistema está diseñado para ayudar a personas que sufrieron discriminación
histórica en la India.

La casta es un sistema social de nacimiento muy antiguo en la
India, que divide a las personas en grupos sociales fijos. Determina
tradicionalmente tu estatus social y tu oficio. No se puede cambiar; naces y
mueres en la misma casta.

Las reservas son un sistema de cuotas obligatorias, donde el gobierno de la
India aparta un porcentaje de lugares exclusivamente para las castas más
bajas (SC, ST, OBC). Estas reservas se aplican principalmente en educación y
empleo.

* BC (Backward Classes): Castas intermedias. Sufren cierta desventaja
  económica o educativa, pero menos extrema que SC o ST.
* OC (Open Category): Categoría General. Personas de castas altas o
  privilegiadas. Tradicionalmente tienen mejor nivel socioeconómico y acceso
  a salud privada.
* Minorities: personas que profesan otras religiones (no hinduista):
  musulmanes, cristianos, budistas, etc.
* SC (Scheduled Castes): Castas Protegidas (históricamente llamados Dalits o
  "intocables"). Comunidades que han sufrido discriminación extrema y pobreza
  severa por siglos.
* ST (Scheduled Tribes): Tribus Protegidas. Comunidades indígenas originarias
  de la India. Suelen vivir en zonas rurales, montañosas o boscosas aisladas,
  con muy poco acceso a hospitales.
"""

# Importamos las librerías

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import io

# Configuración visual general
sns.set_theme(style="whitegrid")  # Estilo de fondo para los gráficos
plt.rcParams["figure.figsize"] = (8, 5)  # Tamaño por defecto de los gráficos

#Carga del dataset
df = pd.read_csv("/content/ntrarogyaseva.csv")

#Limpieza del dataset
# Define los nombres de las columnas según la estructura original, incluyendo un 'ID' para la primera columna
nombres_columnas = [
    'ID', 'AGE', 'SEX', 'CASTE_NAME', 'CATEGORY_CODE', 'CATEGORY_NAME',
    'SURGERY_CODE', 'SURGERY', 'VILLAGE', 'MANDAL_NAME', 'DISTRICT_NAME',
    'PREAUTH_DATE', 'PREAUTH_AMT', 'CLAIM_DATE', 'CLAIM_AMOUNT', 'HOSP_NAME',
    'HOSP_TYPE', 'HOSP_LOCATION', 'HOSP_DISTRICT', 'SURGERY_DATE',
    'DISCHARGE_DATE', 'Mortality Y / N', 'MORTALITY_DATE', 'SRC_REGISTRATION'
]

# Lee el archivo en memoria y elimina las comillas dobles al principio y al final de cada línea
lineas_limpias = []
with open('/content/ntrarogyaseva.csv', 'r', encoding='utf-8') as f:
    for linea in f:
        linea = linea.strip() # Elimina espacios en blanco iniciales/finales y saltos de línea
        if linea.startswith('"') and linea.endswith('"'):
            linea = linea[1:-1] # Elimina la comilla del principio y del final
        lineas_limpias.append(linea)

# Convierte la lista de líneas limpias en un objeto que Pandas pueda leer como un archivo
archivo_limpio = io.StringIO('\n'.join(lineas_limpias))

# Carga el DataFrame usando el archivo preprocesado, especificando los nombres de las columnas y sin encabezado.
# Se quita `index_col=0` para tratar a 'ID' como una columna común en lugar del índice del DataFrame.
# Se usa `on_bad_lines='skip'` para omitir filas mal formateadas, y `dtype=str` para evitar advertencias de tipos mixtos.
df = pd.read_csv(archivo_limpio, header=None, names=nombres_columnas, on_bad_lines='skip', dtype=str)

# La primera fila sigue siendo el encabezado del CSV original, por lo que la eliminamos.
df = df.iloc[1:].copy()

# Limpieza de Mortality Y / N
df["Mortality Y / N"] = df["Mortality Y / N"].replace('17/09/2017 00:00:00', np.nan)
df = df.dropna(subset=['Mortality Y / N'])

# Conversión de tipos
df["AGE"] = pd.to_numeric(df["AGE"], errors='coerce')
df["CLAIM_AMOUNT"] = pd.to_numeric(df["CLAIM_AMOUNT"], errors='coerce')
df["PREAUTH_AMT"] = pd.to_numeric(df["PREAUTH_AMT"], errors='coerce')

# Muestra las primeras filas para verificar el resultado
df.head(3)

# Limpiez de la variable SEX

print("Antes de limpiar")
print(df["SEX"].value_counts())
print()

df["SEX_clean"] = df["SEX"].str.strip().str.lower()
mapeo_sexo = {
    "male":           "Male",
    "female":         "Female",
    "male(child)":    "Male (Child)",
    "female(child)":  "Female (Child)"
}
df["SEX_clean"] = df["SEX_clean"].map(mapeo_sexo)
df["ES_MENOR"] = df["SEX_clean"].str.contains("Child").map({True: "Menor", False: "Adulto"})

print("Después de limpiar")
print(df["SEX_clean"].value_counts())
print()
print("Nulos en SEX_clean:", df["SEX_clean"].isnull().sum())
print()
print("Columna ES_MENOR:")
print(df["ES_MENOR"].value_counts())

"""# PARTE 1 - EXPLORACIÓN GENERAL DE LA POBLACIÓN

## 1.1 Demografía general
"""

# Gráfico 1: Distribución de edades
plt.figure(figsize=(8, 5))
sns.histplot(df["AGE"].dropna(), bins=30, kde=True, color="steelblue")

media = df["AGE"].mean()
mediana = df["AGE"].median()
plt.axvline(media, color="red", linestyle="--", linewidth=1.5, label=f"Promedio: {media:.1f} años")
plt.axvline(mediana, color="orange", linestyle="--", linewidth=1.5, label=f"Mediana: {mediana:.0f} años")

plt.title("Gráfico 1: Distribución de Edades de los Pacientes")
plt.xlabel("Edad")
plt.ylabel("Cantidad de pacientes")
plt.legend()
plt.tight_layout()
plt.show()

"""La edad de los pacientes tiene una mediana de 47 años y un promedio de 44,9 sobre casi 480.000 registros. La distribución se concentra fuerte entre los 35 y los 65 años, justo el rango donde aparecen con más frecuencia las enfermedades que predominan en el dataset (renales, oncológicas y traumatológicas). También hay un pequeño pico en los primeros años de vida, que corresponde a la población pediátrica. Por encima de los 70 años, en cambio, la cantidad de pacientes cae fuerte, algo que puede deberse tanto a causas biológicas como a barreras de acceso para los adultos mayores."""

#Gráfico 2: Distribución de Edad por Grupos
bins   = [0, 17, 34, 49, 64, 110]
labels = ["0–17", "18–34", "35–49", "50–64", "65+"]
df["GRUPO_EDAD"] = pd.cut(df["AGE"], bins=bins, labels=labels, right=True)

orden_castas = ["BC", "OC", "SC", "Minorities", "ST", "Others"]
orden_edad   = ["0–17", "18–34", "35–49", "50–64", "65+"]

plt.figure(figsize=(8, 5))
orden_edad_count = df["GRUPO_EDAD"].value_counts().reindex(orden_edad)
bars = plt.bar(orden_edad_count.index, orden_edad_count.values,
               color="steelblue", edgecolor="white")

total_edad = orden_edad_count.sum()
for bar, val in zip(bars, orden_edad_count.values):
    plt.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 1500,
             f"{val:,}\n({val/total_edad*100:.1f}%)",
             ha="center", va="bottom", fontsize=9)

plt.title("Gráfico 2: Distribución de Pacientes por Grupo de Edad")
plt.xlabel("Grupo de edad")
plt.ylabel("Cantidad de pacientes")
plt.ylim(0, orden_edad_count.max() * 1.2)
plt.tight_layout()
plt.show()

"""Al agrupar la edad en cinco franjas, vemos que el 61,1% de los pacientes está entre los 35 y los 64 años. Los chicos de 0 a 17 años son apenas el 6,5% del total, y los mayores de 65, el 16%. Esta agrupación etaria la vamos a usar más adelante como variable de control, porque la edad es uno de los factores que más influye tanto en la mortalidad como en el tipo de casta que predomina en cada grupo."""

# Gráfico 3: Distribución por Sexo
fig, ax = plt.subplots(figsize=(8, 5))

valores = df["SEX_clean"].value_counts()
colores = ["steelblue", "salmon", "skyblue", "lightcoral"]
bars = ax.bar(valores.index, valores.values, color=colores, edgecolor="white")

total = valores.sum()
for bar, val in zip(bars, valores.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1500,
            f"{val:,}\n({val/total*100:.1f}%)",
            ha="center", va="bottom", fontsize=9)

ax.set_title("Gráfico 3: Distribución de Pacientes por Sexo")
ax.set_xlabel("Sexo")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores.max() * 1.18)
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""Acá aparece el primer dato fuerte de desigualdad: el 54,4% de los pacientes adultos son varones contra el 37,3% de mujeres, una relación de casi 1,5 hombres por cada mujer. Y esa misma brecha se repite en los chicos: 5,2% varones contra 3,1% niñas. Esto puede deberse en parte a que ciertas enfermedades del dataset (como el politrauma) son más comunes en varones, pero también es compatible con que las mujeres, sobre todo en hogares de bajos recursos, tengan más barreras para llegar al sistema de salud."""

# Gráfico 4: Razón de género por grupo etario
sex_grupo = df.groupby(["GRUPO_EDAD", "SEX_clean"]).size().unstack(fill_value=0)

ratio_genero = pd.Series({
    "0–17":  sex_grupo.loc["0–17", "Female (Child)"] / sex_grupo.loc["0–17", "Male (Child)"],
    "18–34": sex_grupo.loc["18–34", "Female"] / sex_grupo.loc["18–34", "Male"],
    "35–49": sex_grupo.loc["35–49", "Female"] / sex_grupo.loc["35–49", "Male"],
    "50–64": sex_grupo.loc["50–64", "Female"] / sex_grupo.loc["50–64", "Male"],
    "65+":   sex_grupo.loc["65+", "Female"] / sex_grupo.loc["65+", "Male"],
})

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(ratio_genero.index, ratio_genero.values, color="#8856a7", edgecolor="white")
ax.axhline(1.0, color="gray", linestyle="--", linewidth=1.2, label="Paridad (1 mujer : 1 hombre)")

for bar, val in zip(bars, ratio_genero.values):
    ax.text(bar.get_x() + bar.get_width()/2, val + 0.02, f"{val:.2f}",
            ha="center", fontsize=9)

ax.set_ylabel("Pacientes mujeres por cada paciente varón")
ax.set_title("Gráfico 4:Razón de género por grupo etario - población general")
ax.set_ylim(0, 1.1)
ax.legend()
plt.tight_layout()
plt.show()

"""Acá medimos, para toda la población, cuántas mujeres llegan al sistema por cada hombre, en cada grupo de edad. El resultado no es parejo: en el grupo de 18 a 34 años hay apenas 0,47 mujeres por cada hombre (la brecha más marcada de todas), mientras que en los adultos de 35 a 64 años esa relación mejora a 0,73-0,78. En los chicos de 0 a 17 la razón es 0,54.

Que la brecha más grande esté en los adultos jóvenes y no en los chicos es un dato interesante: probablemente tiene que ver con que el politrauma y los accidentes, más frecuentes en varones jóvenes que se trasladan en moto o tinene trabajos mas arriesgados físicamente, empujan hacia arriba la cantidad de hombres en esa franja. La brecha en la niñez (0,54) es la que vamos a retomar más adelante, cuando comparemos específicamente BC y OC.
"""

# Gráfico 5: Heatmap Especialidad x Grupo de edad
top10_cat = df["CATEGORY_NAME"].value_counts().head(10).index
sub = df[df["CATEGORY_NAME"].isin(top10_cat)]
tabla = pd.crosstab(sub["CATEGORY_NAME"], sub["GRUPO_EDAD"], normalize="index") * 100

fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(tabla.reindex(columns=orden_edad), annot=True, fmt=".0f",
            cmap="YlOrRd", cbar_kws={"label": "% dentro de la especialidad"}, ax=ax)
ax.set_title("Gráfico 5: Distribución etaria dentro de cada especialidad médica (Top 10)")
ax.set_xlabel("Grupo de edad")
ax.set_ylabel("Especialidad")
plt.tight_layout()
plt.show()

"""Este gráfico cruza cada especialidad médica con la edad de los pacientes que la usan, y permite ver que cada enfermedad "vive" en una franja etaria distinta. Pediatría es, lógicamente, 100% pacientes de 0 a 17 años (control de que la limpieza de datos bien hecha). Las cirugías ortopédicas se concentran en adultos jóvenes (39% tiene entre 18 y 34 años), consistente con fracturas por accidentes. Cardiología y cirugía cardíaca, en cambio, se concentran en mayores de 50 (43% entre 50-64, otro 22-24% en 65+), como es esperable en enfermedades cardiovasculares. Politrauma es la única especialidad que aparece repartida en casi todas las edades, con picos tanto en adultos mayores (25% en 65+, probablemente caídas) como en jóvenes. Este gráfico nos sirve más adelante para entender por qué, cuando comparamos especialidades entre castas, también hay que tener en cuenta la edad de cada grupo.

## 1.2 Perfil clínico y de utilización
"""

# Gráfico 6: Categorías médicas más frecuentes
plt.figure(figsize=(10, 5))
df["CATEGORY_NAME"].value_counts().head(10).plot(kind="barh", color="teal")
plt.title("Gráfico 6: Categorías Médicas más Frecuentes")
plt.xlabel("Casos")
plt.ylabel("Categoría médica")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""Nefrología es, por lejos, la especialidad más utilizada del programa, seguida por Oncología Médica y Politrauma. Esto tiene sentido en el contexto de India: la insuficiencia renal crónica, asociada a diabetes e hipertensión mal controladas, genera una demanda enorme de hemodiálisis. La oncología médica en segundo lugar está muy relacionada con el tratamiento de cáncer de cuello uterino, una enfermedad con alta incidencia en mujeres de bajos recursos. Y el politrauma en tercer lugar refleja accidentes domésticos, laborales o la propia siniestralidad vial de la región."""

# Gráfico 7: Tipo de Hospital
fig, ax = plt.subplots(figsize=(6, 5))

valores_hosp = df["HOSP_TYPE"].value_counts()
etiquetas = {"C": "Corporativo\n(Privado)", "G": "Gobierno\n(Público)"}
bars = ax.bar(
    [etiquetas.get(x, x) for x in valores_hosp.index],
    valores_hosp.values,
    color=["salmon", "steelblue"],
    edgecolor="white", width=0.5
)

total_hosp = valores_hosp.sum()
for bar, val in zip(bars, valores_hosp.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 2000,
            f"{val:,}\n({val/total_hosp*100:.1f}%)",
            ha="center", va="bottom", fontsize=10)

ax.set_title("Gráfico 7: Procedimientos por Tipo de Hospital")
ax.set_ylabel("Cantidad de casos")
ax.set_ylim(0, valores_hosp.max() * 1.18)
plt.tight_layout()

"""El 77% de las atenciones se hacen en hospitales privados y solo el 23% en hospitales públicos. Esto muestra que el programa, aunque está financiado por el Estado, terceriza la mayor parte de la atención al sector privado. Esto es importante porque, más adelante, vamos a ver que la mortalidad en hospitales públicos casi duplica a la de los privados, así que el tipo de hospital al que accede cada grupo termina siendo un factor clave para explicar diferencias de resultado."""

# Gráfico 8: Mortalidad General
fig, ax = plt.subplots(figsize=(6, 5))

valores_mort = df["Mortality Y / N"].value_counts()
bars = ax.bar(["No falleció", "Falleció"],
              valores_mort.values,
              color=["steelblue", "#c94444"],
              edgecolor="white", width=0.5)

total_mort = valores_mort.sum()
for bar, val in zip(bars, valores_mort.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 2000,
            f"{val:,}\n({val/total_mort*100:.2f}%)",
            ha="center", va="bottom", fontsize=10)

ax.set_title("Gráfico 8: Mortalidad de los Pacientes")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores_mort.max() * 1.18)
plt.tight_layout()
plt.show()

"""La mortalidad general del programa es del 2,11%, este número es la "línea de base" contra la que vamos a comparar todo lo que sigue: cuando más adelante hablemos de que BC tiene tal o cual porcentaje de mortalidad, siempre va a ser en relación a este 2,11%.

## 1.3 Selección de grupos para profundizar
"""

# Gráfico 9: Castas
fig, ax = plt.subplots(figsize=(10, 5))

datos = df["CASTE_NAME"].value_counts()
total_casta = datos.sum()

bars = ax.barh(datos.index[::-1], datos.values[::-1],
               color="teal", edgecolor="white")

for bar, val in zip(bars, datos.values[::-1]):
    ax.text(bar.get_width() + 500,
            bar.get_y() + bar.get_height() / 2,
            f"{val:,}  ({val/total_casta*100:.1f}%)",
            va="center", fontsize=9)

ax.set_title("Gráfico 9: Distribución de Pacientes por Casta")
ax.set_xlabel("Cantidad de casos")
ax.set_ylabel("Casta")
ax.set_xlim(0, datos.max() * 1.22)
plt.tight_layout()
plt.show()

"""Acá aparecen las seis castas del dataset. BC concentra más de la mitad de los pacientes (51,3%) y OC el 23,8%, entre las dos suman el 75,1% del total. Las castas históricamente más vulnerables, SC y ST, representan el 16,0% y apenas el 2,7% respectivamente. Esa baja representación de ST, a pesar de ser una población con necesidades de salud importantes, es un primer indicio de que el acceso al programa no es uniforme entre castas."""

# Gráfico 10: Edad según Casta
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="CASTE_NAME", y="AGE", hue="CASTE_NAME",
            order=orden_castas, palette="Set2", legend=False)

medias = df.groupby("CASTE_NAME")["AGE"].mean()
for i, casta in enumerate(orden_castas):
    m = medias[casta]
    plt.text(i, -8, f"x̄={m:.1f}", ha="center", fontsize=9, color="dimgray")

plt.title("Gráfico 10: Distribución de Edad según Casta")
plt.xlabel("Casta")
plt.ylabel("Edad")
plt.ylim(-12, df["AGE"].max() + 5)
plt.tight_layout()
plt.show()

print("Edad promedio por casta:")
print(df.groupby("CASTE_NAME")["AGE"].mean().round(1).sort_values(ascending=False))

"""Cuando miramos la edad promedio de cada casta, aparece un patrón muy ordenado: OC es la casta con pacientes más grandes (49,2 años en promedio) y ST la más joven (38,9 años), con el resto ubicado en el medio según su posición en la jerarquía social. La diferencia entre BC y OC es de 5 años. Esto puede deberse a que las castas más postergadas tienen poblaciones demográficamente más jóvenes, o a que OC, con más acceso a salud privada preventiva, llega más tarde al sistema público. Esta diferencia de edad es importante: la vamos a tener que tener en cuenta cada vez que comparemos mortalidad entre castas, porque la edad por sí sola ya influye mucho en el riesgo de morir."""

# Gráfico 11: Mortalidad por Casta + tamaño de población
mortalidad_casta = (df.groupby("CASTE_NAME")["Mortality Y / N"]
                      .value_counts(normalize=True)
                      .unstack(fill_value=0) * 100)
poblacion_casta = df["CASTE_NAME"].value_counts()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

valores_mort = mortalidad_casta["YES"].reindex(orden_castas)
bars1 = ax1.bar(orden_castas, valores_mort, color="#c94444", edgecolor="white", width=0.6)
ax1.set_title("Tasa de Mortalidad por Casta (%)", fontsize=12)
ax1.set_ylabel("% de pacientes fallecidos")
ax1.set_ylim(0, valores_mort.max() * 1.25)

for bar, val in zip(bars1, valores_mort):
    ax1.text(bar.get_x() + bar.get_width() / 2,
             val + 0.04, f"{val:.2f}%",
             ha="center", va="bottom", fontsize=10)

valores_pob = poblacion_casta.reindex(orden_castas)
total_pob = valores_pob.sum()
bars2 = ax2.bar(orden_castas, valores_pob, color="steelblue", edgecolor="white", width=0.6)
ax2.set_title("Cantidad de Pacientes por Casta (n)", fontsize=12)
ax2.set_ylabel("Cantidad de pacientes")
ax2.set_ylim(0, valores_pob.max() * 1.18)

for bar, val in zip(bars2, valores_pob):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             val + 1000,
             f"{val:,}\n({val/total_pob*100:.1f}%)",
             ha="center", va="bottom", fontsize=9)

plt.suptitle("Gráfico 11: Mortalidad y Representación por Casta", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""Acá se ve la mortalidad de cada casta: ST tiene la más alta (2,44%), seguida de SC (2,28%), Minorities (2,17%), BC (2,08%) y OC con la más baja (1,99%). El orden coincide bastante con la jerarquía social: las castas más postergadas tienden a tener algo más de mortalidad. La diferencia entre BC y OC es de apenas 0,09 puntos porcentuales (chica en términos absolutos, y como vamos a confirmar más adelante con una prueba estadística, no alcanza para decir que sea una diferencia real y no producto del azar). Pero como BC es 5 años más joven que OC, y aun así tiene más mortalidad, esto nos deja una pista importante para seguir investigando."""

# Gráfico 12: Distribución de Sexo dentro de cada Casta
adultos = df[df["SEX_clean"].isin(["Male", "Female"])].copy()
casta_sexo = (adultos.groupby(["CASTE_NAME", "SEX_clean"])
                      .size()
                      .unstack(fill_value=0))
casta_sexo_pct = casta_sexo.div(casta_sexo.sum(axis=1), axis=0) * 100

print("Porcentaje de hombres y mujeres por casta:")
print(casta_sexo_pct.round(1))
print()

ax = casta_sexo_pct.reindex(orden_castas).plot(
    kind="bar",
    stacked=False,
    color=["salmon", "steelblue"],
    figsize=(10, 5),
    edgecolor="white",
    width=0.7
)

plt.title("Gráfico 12: Distribución de Sexo dentro de cada Casta (% adultos)")
plt.xlabel("Casta")
plt.ylabel("Porcentaje (%)")
plt.xticks(rotation=15)
plt.legend(title="Sexo", bbox_to_anchor=(1.01, 1), loc="upper left")

for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f}%",
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.show()

"""Este gráfico es clave para la metodología del trabajo: muestra que BC y OC tienen una composición de género casi idéntica (58,4% y 60,4% varones respectivamente). Esto es una buena noticia para el análisis, porque significa que cualquier diferencia que encontremos más adelante entre BC y OC no se puede explicar porque una casta tenga más hombres que la otra."""

# Gráfico 13: Tipo de Hospital por Casta (BC, OC y resto)
hosp_casta = (df.groupby(["CASTE_NAME", "HOSP_TYPE"])
                .size()
                .unstack(fill_value=0))
hosp_casta_pct = hosp_casta.div(hosp_casta.sum(axis=1), axis=0) * 100

ax = hosp_casta_pct.reindex(orden_castas).rename(
    columns={"G": "Gobierno (Público)", "C": "Corporativo (Privado)"}
).plot(
    kind="bar",
    stacked=False,
    color=["steelblue", "salmon"],
    figsize=(10, 5),
    edgecolor="white",
    width=0.7
)

plt.title("Gráfico 13: Tipo de Hospital según Casta (%)")
plt.xlabel("Casta")
plt.ylabel("Porcentaje (%)")
plt.xticks(rotation=15)
plt.legend(title="Tipo de Hospital", bbox_to_anchor=(1.01, 1), loc="upper left")

for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f}%",
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.show()

"""OC accede al sector privado en el 82,7% de los casos, BC en el 75,8%, una diferencia de casi 7 puntos. ST, la casta más postergada, es la que menos accede a lo privado (69,1%). Como la mortalidad en el sector público es mucho más alta que en el privado, este gráfico empieza a sugerir que el tipo de hospital al que accede cada casta puede estar mediando parte de las diferencias de mortalidad que vimos en el Gráfico 11.

## Cierre Parte 1
Elegimos profundizar específicamente en BC y OC por tres razones: primero, son las dos castas con más representatividad estadística del dataset (75,1% del total combinado); segundo, tienen una composición de género prácticamente idéntica, lo que permite aislar el efecto de la casta sin que el género lo contamine; y tercero, ya en esta primera mirada general aparecen diferencias de edad, mortalidad y acceso al sector privado entre ambas que ameritan un análisis más profundo. A partir de acá, todos los gráficos comparan exclusivamente estos dos grupos.

# PARTE 2 - COMPARACIÓN BC vs OC

## 2.1 Perfil demográfico BC vs OC
"""

# Subconjunto de trabajo: solo BC y OC, adultos (Male/Female)
df_bc_oc = df[df["CASTE_NAME"].isin(["BC", "OC"])].copy()
df_bc_oc_adultos = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male", "Female"])].copy()

colores_casta = {"BC": "#4C72B0", "OC": "#DD8452"}

# Gráfico 14: Edad por Casta y Sexo (BC vs OC)
plt.figure(figsize=(8, 6))
sns.boxplot(data=df_bc_oc_adultos, x="CASTE_NAME", y="AGE",
            hue="SEX_clean", order=["BC", "OC"],
            palette=["salmon", "steelblue"])

plt.title("Gráfico 14: Distribución de Edad por Casta y Sexo (BC vs OC)")
plt.xlabel("Casta")
plt.ylabel("Edad")
plt.legend(title="Sexo")
plt.tight_layout()
plt.show()

print("Edad promedio - BC vs OC, por sexo:")
print(df_bc_oc_adultos.groupby(["CASTE_NAME", "SEX_clean"])["AGE"].mean().round(1))

"""Acá desagregamos la diferencia de edad del Gráfico 10 por sexo, para asegurarnos de que no sea un artefacto. Y no lo es: tanto entre varones como entre mujeres, los pacientes de OC son sistemáticamente más grandes que los de BC, manteniendo esa brecha de unos 5 años en ambos casos. Esto refuerza la idea de que la diferencia de edad es un efecto real asociado a la casta, no algo que aparece solo en un sexo."""

# Gráfico 15: Brecha de género en el acceso, niñez vs adultez, BC vs OC
colores_casta = {"BC": "#4C72B0", "OC": "#DD8452"}
ratios = pd.DataFrame({
    "BC": [0.601, 0.708],
    "OC": [0.568, 0.657]
}, index=["Niñas / Niños (0–17)", "Mujeres / Hombres (18+)"])

fig, ax = plt.subplots(figsize=(8, 5))
ratios.plot(kind="bar", ax=ax, color=[colores_casta["BC"], colores_casta["OC"]],
            edgecolor="white", width=0.7)
ax.axhline(1.0, color="gray", linestyle="--", linewidth=1, label="Paridad (1:1)")
ax.set_ylabel("Pacientes mujeres por cada paciente varón")
ax.set_title("Gráfico 15: Brecha de género en el acceso al sistema: niñez vs adultez (BC vs OC)")
ax.set_xticklabels(ratios.index, rotation=10)
ax.legend(title="Casta")

# Etiquetas con el valor arriba de cada barra
for contenedor in ax.containers:
    if hasattr(contenedor, "patches"):  # evita la línea de paridad
        ax.bar_label(contenedor, fmt="%.2f", padding=3, fontsize=9)

ax.set_ylim(0, 1.05)
plt.tight_layout()
plt.show()

"""Este es uno de los hallazgos más interesantes del trabajo. Si contamos cuántas mujeres llegan al sistema por cada hombre, separando niñez de adultez, vemos que la brecha es mucho más marcada en los chicos que en los adultos: en BC hay 0,60 niñas por cada niño tratado, y en OC 0,57. En adultos, la brecha se achica bastante: 0,71 en BC y 0,66 en OC. Es decir, en las dos castas faltan más niñas que mujeres adultas, en relación a los varones. Y es un poco contraintuitivo que la brecha sea más marcada en OC, la casta de mayor nivel socioeconómico, porque uno esperaría que más recursos signifique menos sesgo de género, acá no es así."""

# Gráfico 16: Edad promedio al ingreso, niñas vs niños (BC vs OC)
# Define df_bc_oc para asegurar que esté disponible en esta celda
df_bc_oc = df[df["CASTE_NAME"].isin(["BC", "OC"])].copy()

ninos_bc_oc = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male (Child)", "Female (Child)"])]

edad_prom = ninos_bc_oc.groupby(["CASTE_NAME", "SEX_clean"])["AGE"].mean().unstack()

fig, ax = plt.subplots(figsize=(8, 5))
x = range(len(["BC", "OC"]))
ancho = 0.35
for i, sexo in enumerate(["Male (Child)", "Female (Child)"]):
    valores = edad_prom[sexo].reindex(["BC", "OC"])
    bars = ax.bar([xi + i*ancho for xi in x], valores, width=ancho,
                  label=sexo, color=["steelblue", "salmon"][i], edgecolor="white")
    for bar, val in zip(bars, valores):
        ax.text(bar.get_x()+bar.get_width()/2, val+0.05, f"{val:.2f}",
                ha="center", fontsize=9)

ax.set_xticks([xi + ancho/2 for xi in x])
ax.set_xticklabels(["BC", "OC"])
ax.set_ylabel("Edad promedio (años)")
ax.set_title("Gráfico 16: Edad promedio al ingreso al sistema — niñas vs niños (BC vs OC)")
ax.legend(title="Sexo")
plt.tight_layout()
plt.show()

"""Acá completamos el gráfico anterior con un dato más fino: entre los chicos que sí llegan a ser atendidos, las niñas son sistemáticamente más chicas que los niños al momento de la consulta. En BC, las niñas tienen en promedio 3,62 años contra 4,15 de los niños; en OC, 3,80 contra 4,95. Esta diferencia es estadísticamente muy sólida. Una explicación posible es que las familias llevan a las niñas al sistema solo ante cuadros más urgentes, que no admiten espera, mientras que a los niños los llevan también por motivos menos graves a lo largo de un rango de edad más amplio. Esto explicaría también que la mortalidad de niñas y niños termina siendo parecida, a pesar de que las niñas llegan, en promedio, con cuadros más urgentes.

## 2.2 Resultados clínicos BC vs OC
"""

# Gráfico 17: Mortalidad por Grupo de Edad - BC vs OC
mort_edad_casta = (df_bc_oc.groupby(["GRUPO_EDAD", "CASTE_NAME"])["Mortality Y / N"]
                           .apply(lambda x: (x == "YES").mean() * 100)
                           .unstack(fill_value=0)
                           .reindex(orden_edad))

n_edad_casta = (df_bc_oc.groupby(["GRUPO_EDAD", "CASTE_NAME"])
                        .size()
                        .unstack(fill_value=0)
                        .reindex(orden_edad))

fig, ax = plt.subplots(figsize=(11, 6))
x = range(len(orden_edad))
ancho = 0.35

for i, casta in enumerate(["BC", "OC"]):
    valores = mort_edad_casta[casta]
    bars = ax.bar([xi + i * ancho for xi in x], valores,
                   width=ancho, label=casta, color=colores_casta[casta], edgecolor="white")
    for bar, val, n_val in zip(bars, valores, n_edad_casta[casta]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                val + 0.05,
                f"{val:.2f}%\n(n={n_val:,})",
                ha="center", va="bottom", fontsize=8)

ax.set_title("Gráfico 17: Tasa de Mortalidad por Grupo de Edad — BC vs OC")
ax.set_xlabel("Grupo de edad")
ax.set_ylabel("% mortalidad")
ax.set_xticks([xi + ancho / 2 for xi in x])
ax.set_xticklabels(orden_edad)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""BC tiene más mortalidad que OC en todos los grupos de edad, pero la diferencia no es pareja: es más grande en los chicos (1,08% vs 0,74%, una diferencia de 0,34 puntos) y en los jóvenes de 18 a 34 (1,33% vs 1,03%), y prácticamente desaparece en los mayores de 65 (3,11% vs 3,08%). Que la brecha sea más grande justo donde la mortalidad esperada es más baja es un dato que llama la atención: ahí cualquier exceso de mortalidad es proporcionalmente mucho más importante. En los adultos mayores, en cambio, parece que el peso de la edad biológica termina dominando por sobre cualquier factor social."""

# Gráfico 18: Mortalidad por Grupo de Edad - BC vs OC
import scipy.stats as st

resultados = []
for g in orden_edad:
    sub = df_bc_oc[df_bc_oc["GRUPO_EDAD"] == g]
    bc = sub[sub["CASTE_NAME"]=="BC"]["Mortality Y / N"]
    oc = sub[sub["CASTE_NAME"]=="OC"]["Mortality Y / N"]
    p_bc, p_oc = (bc=="YES").mean(), (oc=="YES").mean()
    diff = (p_bc - p_oc) * 100
    se = np.sqrt(p_bc*(1-p_bc)/len(bc) + p_oc*(1-p_oc)/len(oc)) * 100
    resultados.append((g, diff, diff-1.96*se, diff+1.96*se))

res_df = pd.DataFrame(resultados, columns=["Grupo","Diferencia","IC_low","IC_high"])

fig, ax = plt.subplots(figsize=(8,5))
ax.errorbar(res_df["Diferencia"], res_df["Grupo"],
            xerr=[res_df["Diferencia"]-res_df["IC_low"], res_df["IC_high"]-res_df["Diferencia"]],
            fmt="o", color="#c94444", capsize=4)
ax.axvline(0, color="gray", linestyle="--")
ax.set_xlabel("Diferencia BC − OC en mortalidad, IC 95%")
ax.set_title("Gráfico 18: Forest plot: diferencia de mortalidad por grupo de edad")
plt.tight_layout()
plt.show()

"""Este gráfico es la versión "con prueba estadística" del anterior: para cada grupo de edad, calculamos la diferencia BC menos OC y le pusimos un intervalo de confianza del 95%. Cuando ese intervalo no toca la línea del cero, podemos decir que la diferencia es estadísticamente significativa y no un efecto del azar. Acá vemos que eso pasa claramente en los grupos de 18 a 34 y de 35 a 49 años; en 0-17 y 50-64 el intervalo roza el cero, así que la evidencia es más débil; y en 65+ el intervalo cruza ampliamente el cero, confirmando que ahí no hay diferencia real entre BC y OC. Este gráfico es importante porque nos obliga a ser más cuidadosos: no en todos los grupos de edad podemos afirmar con seguridad que BC tiene peor mortalidad que OC."""

pop_estandar = df["GRUPO_EDAD"].value_counts(normalize=True)

def tasa_ajustada(casta):
    sub = df_bc_oc[df_bc_oc["CASTE_NAME"] == casta]
    tasas = sub.groupby("GRUPO_EDAD")["Mortality Y / N"].apply(lambda x: (x=="YES").mean())
    return (tasas * pop_estandar).sum() * 100

comparacion = pd.DataFrame({
    "Cruda": [
        (df_bc_oc[df_bc_oc.CASTE_NAME=="BC"]["Mortality Y / N"]=="YES").mean()*100,
        (df_bc_oc[df_bc_oc.CASTE_NAME=="OC"]["Mortality Y / N"]=="YES").mean()*100
    ],
    "Ajustada por edad": [tasa_ajustada("BC"), tasa_ajustada("OC")]
}, index=["BC", "OC"])

fig, ax = plt.subplots(figsize=(8, 5))
comparacion.plot(kind="bar", ax=ax, color=["#bbbbbb", "#c94444"], edgecolor="white")
ax.set_ylabel("% mortalidad")
ax.set_title("Gráfico 19: Mortalidad cruda vs. ajustada por edad - BC vs OC")
ax.set_xticklabels(comparacion.index, rotation=0)
ax.legend(loc="upper left", bbox_to_anchor=(1.02, 0.5))

plt.tight_layout()
plt.show()

"""Como BC es 5 años más joven que OC, comparar las mortalidades "crudas" (2,08% vs 1,99%) no es del todo justo: si ambas castas tuvieran la misma estructura de edad, ¿la diferencia sería mayor o menor? Para responder esto, recalculamos la mortalidad de cada casta como si tuviera la misma distribución de edad que la población total (estandarización). El resultado es revelador: la mortalidad ajustada de BC casi no cambia (de 2,08% a 1,99%), pero la de OC baja bastante más (de 1,99% a 1,80%). Es decir, la brecha entre BC y OC se duplica una vez que controlamos por edad. Esto confirma la hipótesis que veníamos planteando: parte de la "ventaja" que parecía tener OC en la comparación cruda en realidad se debía a que sus pacientes son más jóvenes; al sacar ese efecto, la diferencia real es más grande de lo que parecía."""

# Gráfico 20: Especialidades Médicas - BC vs OC
top8_general = df_bc_oc_adultos["CATEGORY_NAME"].value_counts().head(8).index.tolist()
df_top8_bc_oc = df_bc_oc_adultos[df_bc_oc_adultos["CATEGORY_NAME"].isin(top8_general)].copy()

esp_casta = (df_top8_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"])
                          .size()
                          .unstack(fill_value=0))
esp_casta_pct = esp_casta.div(esp_casta.sum(axis=0), axis=1) * 100
esp_casta_pct = esp_casta_pct.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(11, 7))
y = range(len(esp_casta_pct))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], esp_casta_pct["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], esp_casta_pct["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars in [bars_bc, bars_oc]:
    for bar in bars:
        val = bar.get_width()
        ax.text(val + 0.4, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(esp_casta_pct.index, fontsize=9)
ax.set_title("Gráfico 20: Especialidades Médicas (Top 8) — BC vs OC")
ax.set_xlabel("% dentro de cada casta")
ax.set_xlim(0, esp_casta_pct.max().max() * 1.2)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""Acá el perfil de especialidades entre BC y OC resulta bastante parecido en la mayoría de los casos: en Politrauma, por ejemplo, la proporción es prácticamente la misma (16,7% en BC vs 16,3% en OC), así que ahí no hay una diferencia real de uso del sistema. La especialidad donde sí aparece la brecha más marcada es justamente Nefrología, la más usada por ambas castas: OC la utiliza proporcionalmente más que BC (24,9% vs 21,4%, casi 3,5 puntos de diferencia). Este dato es importante para lo que viene después: si OC concentra proporcionalmente más pacientes en Nefrología que BC, y aun así (gráfico 25) es BC quien tiene mayor mortalidad dentro de esa misma especialidad, la brecha de resultado no se explica por una diferencia en la "carga" de casos complejos que recibe cada casta. El resto de las especialidades muestra diferencias menores y sin un patrón tan claro (Cirugía Cardíaca algo más frecuente en OC; Cirugía Genitourinaria y Oncología Radiante, algo más en BC)."""

# Gráfico 21: Top 10 Cirugías - BC vs OC
fig, axes = plt.subplots(1, 2, figsize=(15, 7))

for ax, casta in zip(axes, ["BC", "OC"]):
    subset = df_bc_oc_adultos[df_bc_oc_adultos["CASTE_NAME"] == casta]
    top10_cirugias = subset["SURGERY"].value_counts().head(10)
    total_casta_n = len(subset)
    pct = top10_cirugias / total_casta_n * 100

    bars = ax.barh(top10_cirugias.index[::-1], pct.values[::-1],
                   color=colores_casta[casta], edgecolor="white")

    for bar, val in zip(bars, pct.values[::-1]):
        ax.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

    ax.set_title(f"{casta}  (n = {total_casta_n:,})", fontsize=11, fontweight="bold")
    ax.set_xlabel("% de casos")
    ax.set_xlim(0, pct.max() * 1.2)
    ax.tick_params(axis='y', labelsize=8)

plt.suptitle("Gráfico 21: Top 10 Cirugías más Frecuentes — BC vs OC", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""A pesar de la diferencia de especialidades del gráfico anterior, cuando miramos las cirugías puntuales, BC y OC se parecen bastante: las dos tienen como primer procedimiento la hemodiálisis de mantenimiento (14,2% en BC, 18,3% en OC) y como segundo la cirugía de fracturas (10,8% y 11,7%). Esto nos dice que el tipo de procedimiento, en sí mismo, no es lo que más diferencia a las dos castas, hay que buscar las diferencias en otro lado, como la gravedad con la que llegan los pacientes o la calidad de la atención que reciben."""

# Gráfico 22: Mortalidad por Tipo de Hospital - BC vs OC
mort_hosp_casta = (df_bc_oc.groupby(["HOSP_TYPE", "CASTE_NAME"])["Mortality Y / N"]
                           .apply(lambda x: (x == "YES").mean() * 100)
                           .unstack(fill_value=0))

n_hosp_casta = (df_bc_oc.groupby(["HOSP_TYPE", "CASTE_NAME"]).size().unstack(fill_value=0))

etiquetas_hosp = {"G": "Gobierno (Público)", "C": "Corporativo (Privado)"}

fig, ax = plt.subplots(figsize=(9, 6))
x = range(len(mort_hosp_casta.index))
ancho = 0.35

for i, casta in enumerate(["BC", "OC"]):
    valores = mort_hosp_casta[casta]
    bars = ax.bar([xi + i * ancho for xi in x], valores,
                   width=ancho, label=casta, color=colores_casta[casta], edgecolor="white")
    for bar, val, hosp_idx in zip(bars, valores, mort_hosp_casta.index):
        n_val = n_hosp_casta.loc[hosp_idx, casta]
        ax.text(bar.get_x() + bar.get_width() / 2,
                val + 0.05,
                f"{val:.2f}%\n(n={n_val:,})",
                ha="center", va="bottom", fontsize=8)

ax.set_title("Gráfico 22: Tasa de Mortalidad por Tipo de Hospital — BC vs OC")
ax.set_xlabel("Tipo de hospital")
ax.set_ylabel("% mortalidad")
ax.set_xticks([xi + ancho / 2 for xi in x])
ax.set_xticklabels([etiquetas_hosp.get(i, i) for i in mort_hosp_casta.index])
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""Acá aparece algo interesante: en los hospitales públicos, BC tiene más mortalidad que OC (3,73% vs 3,53%), pero en los hospitales privados pasa al revés, OC tiene un poquito más (1,83% vs 1,72). Lo más importante de este gráfico, sin embargo, no es esa pequeña inversión, sino el hecho de que en ambas castas la mortalidad en el sector público casi duplica a la del privado. Esto confirma que el tipo de hospital es un factor mucho más determinante para el resultado clínico que la casta en sí misma."""

# Gráfico 23: Distribución Geográfica - BC vs OC
top_distritos = df_bc_oc_adultos["DISTRICT_NAME"].value_counts().head(10).index.tolist()
df_distritos = df_bc_oc_adultos[df_bc_oc_adultos["DISTRICT_NAME"].isin(top_distritos)].copy()

dist_casta = (df_distritos.groupby(["DISTRICT_NAME", "CASTE_NAME"])
                          .size()
                          .unstack(fill_value=0))
dist_casta_pct = dist_casta.div(dist_casta.sum(axis=1), axis=0) * 100
dist_casta_pct = dist_casta_pct.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))
y = range(len(dist_casta_pct))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], dist_casta_pct["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], dist_casta_pct["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars in [bars_bc, bars_oc]:
    for bar in bars:
        val = bar.get_width()
        ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(dist_casta_pct.index, fontsize=9)
ax.set_title("Gráfico 23: Distribución por Distrito (Top 10) — BC vs OC")
ax.set_xlabel("% dentro de cada casta")
ax.set_xlim(0, dist_casta_pct.max().max() * 1.2)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""Este gráfico muestra que la composición de castas cambia muchísimo según la zona geográfica. En el norte Srikakulam, casi el 94% de los pacientes son BC; en distritos del centro-sur, como Guntur, la proporción está mucho más pareja (52,5% BC, 47,5% OC). Esto es un dato metodológico importante: si la calidad de los hospitales también varía según el distrito, parte de las diferencias que le atribuimos a la casta en realidad podrían deberse a dónde vive cada paciente, no a la casta en sí."""

# Gráfico 24: Razón niñas/niños por distrito (top 10)
ninos_bc_oc = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male (Child)", "Female (Child)"])]
top10d = df_bc_oc["DISTRICT_NAME"].value_counts().head(10).index

d = ninos_bc_oc[ninos_bc_oc["DISTRICT_NAME"].isin(top10d)].groupby(
        ["DISTRICT_NAME","SEX_clean"]).size().unstack(fill_value=0)
d["ratio"] = d["Female (Child)"] / d["Male (Child)"]
d = d.sort_values("ratio")

fig, ax = plt.subplots(figsize=(9,6))
bars = ax.barh(d.index, d["ratio"], color="#8856a7", edgecolor="white")
ax.axvline(1.0, color="gray", linestyle="--", label="Paridad (1:1)")
for bar, val in zip(bars, d["ratio"]):
    ax.text(val+0.01, bar.get_y()+bar.get_height()/2, f"{val:.2f}", va="center", fontsize=8)
ax.set_xlabel("Niñas por cada niño tratado")
ax.set_title("Gráfico 24: Razón de género infantil por distrito (Top 10, BC+OC)")
ax.legend()
plt.tight_layout()
plt.show()

"""Acá retomamos la historia de la brecha de género, pero mirándola por geografía: la razón de niñas por niño varía bastante de un distrito a otro, desde 0,55 en Vishakhapatnam hasta 0,73 en West Godavari,una diferencia de 0,17 puntos, que es bastante más grande que la diferencia entre BC y OC que vimos en el Gráfico 15. Esto sugiere algo importante: el lugar donde vive una familia puede pesar más en la brecha de género de acceso a salud que la casta a la que pertenece. Es una buena pista para futuras investigaciones, aunque con los datos que tenemos no podemos explicar por qué Krishna está tan por debajo del resto."""

# Gráfico 25: Mortalidad por Especialidad - BC vs OC
top6_especialidades = df_bc_oc["CATEGORY_NAME"].value_counts().head(6).index.tolist()
df_top6_bc_oc = df_bc_oc[df_bc_oc["CATEGORY_NAME"].isin(top6_especialidades)].copy()

mort_esp_casta = (df_top6_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"])["Mortality Y / N"]
                                .apply(lambda x: (x == "YES").mean() * 100)
                                .unstack(fill_value=0))

n_esp_casta = (df_top6_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"]).size().unstack(fill_value=0))

mort_esp_casta = mort_esp_casta.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))
y = range(len(mort_esp_casta))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], mort_esp_casta["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], mort_esp_casta["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars, casta in zip([bars_bc, bars_oc], ["BC", "OC"]):
    for bar, esp in zip(bars, mort_esp_casta.index):
        val = bar.get_width()
        n_val = n_esp_casta.loc[esp, casta]
        ax.text(val + 0.05, bar.get_y() + bar.get_height() / 2,
                f"{val:.2f}% (n={n_val:,})", va="center", fontsize=7)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(mort_esp_casta.index, fontsize=9)
ax.set_title("Gráfico 25: Tasa de Mortalidad por Especialidad (Top 6) — BC vs OC")
ax.set_xlabel("% mortalidad")
ax.set_xlim(0, mort_esp_casta.max().max() * 1.4)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""Este es el gráfico más importante de todo el trabajo, porque es el único cruce donde la diferencia de mortalidad entre BC y OC se sostiene con una prueba estadística sólida: dentro de Nefrología, BC tiene 4,08% de mortalidad contra 3,54% de OC, una diferencia que no es casualidad. En las otras cinco especialidades (Cirugía Cardíaca, Cirugía General, Politrauma, Oncología Médica y Cirugía Genitourinaria) las diferencias son chiquitas o inexistentes. Que la brecha se concentre justo en Nefrología, la especialidad más usada del programa y la que incluye la hemodiálisis crónica, es un hallazgo que sugiere que hay algo específico de esa enfermedad, tal vez acceso más tardío al tratamiento, o diferencias en la calidad de las unidades de diálisis a las que accede cada casta (dato que conecta con la diferencia de acceso al sector privado que vimos en el Gráfico 13, no en el 12) que está generando una desventaja real para los pacientes BC.

# CONCLUSIONES
El análisis comparativo entre BC y OC revela dos tipos de desigualdad de naturaleza distinta. Por un lado, una desigualdad de resultado clínico, acotada y específica: dentro de Nefrología, la especialidad de mayor carga del programa, BC presenta una mortalidad significativamente superior a OC, sin que esta brecha se replique en las demás especialidades. Por otro lado, una desigualdad de acceso por género, transversal a ambas castas y más marcada en la niñez que en la adultez: las niñas representan apenas 0,60 (BC) y 0,57 (OC) pacientes por cada niño tratado, y las que sí acceden lo hacen significativamente más jóvenes que los niños, lo cual sugiere un umbral de severidad más alto para que una niña sea llevada al sistema. Esta segunda forma de desigualdad no se explica por la casta, es similar o incluso algo peor en OC, la categoría socioeconómicamente más privilegiada, sino que parece operar como un patrón social más amplio, posiblemente vinculado a dinámicas de preferencia de género en la búsqueda de atención médica dentro del hogar, documentadas en la literatura sobre salud pública en India.

## Síntesis del estudio
El presente trabajo analizó 479.688 registros del programa de salud pública NTR Aarogyaseva, con el objetivo de caracterizar a la población cubierta y evaluar si existen diferencias sistemáticas en el acceso y los resultados de salud entre dos categorías del sistema de castas indio: Backward Classes (BC) y Open Category (OC). La elección de estos dos grupos —que en conjunto representan el 75,1% del dataset— respondió a un criterio de representatividad estadística y a la necesidad de aislar el efecto de la casta de otros factores de confusión, particularmente el género, dado que ambas categorías presentan una composición de sexo prácticamente equivalente. El análisis combinó estadística descriptiva, pruebas de significancia (chi-cuadrado, t-test), estandarización de tasas por edad y desagregación geográfica, lo que permitió ir más allá de la comparación de porcentajes brutos y establecer con mayor precisión en qué dimensiones la desigualdad observada es estadísticamente sostenible y en cuáles no.

## Principales hallazgos
**Sobre la población general.** El programa atiende mayoritariamente a adultos de 35 a 64 años (61,2% del total), con un marcado predominio masculino (62% de los registros) y una fuerte dependencia del sector hospitalario privado (77% de los procedimientos), pese a tratarse de un programa financiado públicamente. El perfil epidemiológico está dominado por la enfermedad renal crónica —que explica la centralidad de la hemodiálisis de mantenimiento como procedimiento más frecuente del dataset—, seguida por la oncología y el politrauma.

**Sobre la desigualdad de resultado clínico entre BC y OC.** La comparación bruta de mortalidad (BC: 2,08%; OC: 1,99%) no resultó estadísticamente significativa (χ²=3,12; p=0,077), un resultado que matiza cualquier afirmación general de que "BC tiene peor mortalidad que OC". Sin embargo, dos análisis más finos revelan una desigualdad real, aunque acotada:
1. Al estandarizar las tasas por edad —dado que los pacientes OC son en promedio 5 años mayores que los BC— la brecha de mortalidad se duplica, pasando de 0,09 a 0,19 puntos porcentuales. Esto indica que la comparación cruda subestimaba la verdadera desventaja relativa de BC, al estar parcialmente compensada por su perfil etario más joven.
2. Al desagregar por especialidad médica, la única diferencia de mortalidad estadísticamente significativa entre BC y OC se concentra en Nefrología (BC: 4,08%; OC: 3,54%; p=0,0014), la especialidad de mayor peso del programa. En las cinco especialidades restantes —incluidas Oncología Médica, Politrauma y Cirugía Cardíaca— las diferencias son nulas o estadísticamente indistinguibles del azar.

La concentración de la brecha en una sola especialidad, y su desaparición en las demás, es un resultado metodológicamente más sólido y más interesante que una afirmación genérica de inequidad: sugiere que el factor que perjudica a los pacientes BC no opera de manera uniforme en todo el sistema de salud, sino en un punto específico del recorrido asistencial —el tratamiento crónico de la enfermedad renal— donde la severidad clínica al ingreso, el acceso a diálisis de calidad o la prevalencia de comorbilidades no controladas podrían estar jugando un rol.

**Sobre la desigualdad de acceso por género.** El hallazgo más relevante del trabajo, en términos de su alcance social, no aparece al comparar mortalidad sino al comparar quién llega al sistema. En ambas castas, la proporción de niñas tratadas por cada niño tratado es marcadamente inferior a la paridad (BC: 0,60; OC: 0,57), y esa brecha es sistemáticamente mayor en la niñez que en la adultez (donde la razón mejora a 0,71 en BC y 0,66 en OC). Más aún, entre los pacientes pediátricos, las niñas que sí acceden al sistema lo hacen a una edad significativamente menor que los niños, un patrón compatible con la idea de que las familias llevan a las niñas a recibir atención únicamente ante cuadros de mayor urgencia.

A pesar de esta selección hacia casos más severos, la mortalidad de niñas y niños tratados no difiere de manera significativa. Esto permite una distinción central para las conclusiones del trabajo: la inequidad de género detectada no se ubica en la calidad de la atención que el sistema brinda una vez que la paciente ingresa, sino en la decisión previa de búsqueda de atención dentro del hogar. Es, en otras palabras, una desigualdad de acceso, no de resultado clínico.

Un dato adicional refuerza la relevancia social de este hallazgo: la brecha de género varía mucho más por distrito geográfico (entre 0,54 en Krishna y 0,71 en West Godavari, una diferencia de 0,17 puntos) que entre BC y OC (diferencia de apenas 0,03 puntos). Esto sugiere que, en lo que respecta al acceso diferencial por género, el territorio —con sus particularidades culturales, económicas y de infraestructura sanitaria— pesa más que la pertenencia a una casta determinada.

## Hechos, interpretaciones e hipótesis
Para mantener el rigor exigido a un trabajo de esta naturaleza, es necesario distinguir explícitamente tres niveles de afirmación:

* Hechos observados: las diferencias de edad, mortalidad por especialidad, acceso al sector privado y composición de género del acceso están sustentados directamente por los datos y, en los casos relevantes, por pruebas de significancia estadística.
* Interpretaciones: que la brecha de mortalidad en Nefrología refleje una desventaja real asociada a la casta, o que la brecha de género refleje una decisión diferencial de búsqueda de atención, son lecturas razonables de los datos, pero exceden lo que un análisis puramente descriptivo puede demostrar por sí solo.
* Hipótesis explicativas: la atribución de estos patrones a causas específicas —menor acceso preventivo, mayor prevalencia de comorbilidades no controladas, preferencia de género en la búsqueda de atención médica— son conjeturas razonables, consistentes con la literatura sobre salud pública en India, pero no pueden confirmarse con las variables disponibles en este dataset, que no incluye información sobre severidad clínica al ingreso, comorbilidades ni decisiones familiares.

## Limitaciones del estudio
El carácter observacional y administrativo del dataset impide establecer relaciones causales. No se dispone de variables clínicas de severidad al ingreso (estadio de la enfermedad renal, comorbilidades, tiempo de evolución), lo que limita la interpretación de las diferencias de mortalidad como atribuibles exclusivamente a la casta. La variable distrito emerge como un posible factor de confusión no controlado simultáneamente con la casta en los análisis de mortalidad, dada la marcada heterogeneidad geográfica en la composición de castas (de 94% BC en Srikakulam a 52,5% en Guntur). Finalmente, el dataset no contiene información sobre la población elegible que no accede al sistema, por lo que las conclusiones sobre "acceso" se basan en comparaciones relativas dentro de quienes efectivamente fueron atendidos, y no en una medición directa de la demanda insatisfecha.

## Relevancia del hallazgo
Más allá de su valor académico, el trabajo identifica dos problemas de naturaleza distinta que ameritarían intervenciones diferentes si se buscara reducir la inequidad en el programa: una intervención clínica focalizada en la calidad y oportunidad del tratamiento nefrológico para la población BC, y una intervención de tipo social o comunicacional orientada a modificar los patrones de búsqueda de atención médica para niñas, que no se resuelve mejorando la atención hospitalaria sino actuando antes, en la decisión de consultar.

# PARTE 3 - MODELO PREDICTIVO: Predicción de Mortalidad

Se busca predecir, a partir de información disponible al momento de la preautorización del procedimiento (es decir, antes de conocer el desenlace), si un paciente fallecerá durante el episodio cubierto por el seguro. Es un problema de clasificación binaria, con una fuerte particularidad: la clase positiva (fallecimiento) representa apenas el 2,06% de los casos dentro del subconjunto BC/OC, por lo que el desbalance de clases debe tratarse explícitamente en todo el desarrollo.
"""
