# -*- coding: utf-8 -*-
"""ntrarogyaseva base taller .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nGcCxjpKtvylygT1wvlpECx4nA3Agp20

# Dataset

Dataset con aprox 480.000 registros de pacientes que recibieron cirugías/procedimientos médicos cubiertos por un seguro de salud público de India.

Incluye info del paciente, del hospital, del procedimiento, montos autorizados y cobrados, y si el paciente falleció.
"""

# Importamos las librerías

import pandas as pd

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

import base64
import io
import json
import os
from datetime import datetime, timezone

def fig_to_base64(fig) -> str:
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=120)
    buf.seek(0)
    encoded = base64.b64encode(buf.read()).decode('utf-8')
    plt.close(fig)
    return encoded

charts = []
chart_counter = 1

def add_chart(fig):
    global chart_counter
    try:
        chart_id = f"chart_{chart_counter:02d}"
        title = f"Chart {chart_counter}"
        if fig._suptitle:
            title = fig._suptitle.get_text()
        elif fig.axes and fig.axes[0].get_title():
            title = fig.axes[0].get_title()
            
        charts.append({'id': chart_id, 'title': title,
                       'type': 'image/png', 'data': fig_to_base64(fig)})
        print(f'  [OK] {chart_id}')
        chart_counter += 1
    except Exception as e:
        print(f'  [WARN] No se pudo generar chart: {e}')

import seaborn as sns
import numpy as np

# Configuración visual general
sns.set_theme(style="whitegrid")  # Estilo de fondo para los gráficos
plt.rcParams["figure.figsize"] = (8, 5)  # Tamaño por defecto de los gráficos

import io
import os

# Define los nombres de las columnas según la estructura original, incluyendo un 'ID' para la primera columna
nombres_columnas = [
    'ID', 'AGE', 'SEX', 'CASTE_NAME', 'CATEGORY_CODE', 'CATEGORY_NAME',
    'SURGERY_CODE', 'SURGERY', 'VILLAGE', 'MANDAL_NAME', 'DISTRICT_NAME',
    'PREAUTH_DATE', 'PREAUTH_AMT', 'CLAIM_DATE', 'CLAIM_AMOUNT', 'HOSP_NAME',
    'HOSP_TYPE', 'HOSP_LOCATION', 'HOSP_DISTRICT', 'SURGERY_DATE',
    'DISCHARGE_DATE', 'Mortality Y / N', 'MORTALITY_DATE', 'SRC_REGISTRATION'
]

# Lee el archivo en memoria y elimina las comillas dobles al principio y al final de cada línea
lineas_limpias = []
with open(os.path.join(os.path.dirname(__file__), 'ntrarogyaseva.csv'), 'r', encoding='utf-8') as f:
    for linea in f:
        linea = linea.strip() # Elimina espacios en blanco iniciales/finales y saltos de línea
        if linea.startswith('"') and linea.endswith('"'):
            linea = linea[1:-1] # Elimina la comilla del principio y del final
        lineas_limpias.append(linea)

# Convierte la lista de líneas limpias en un objeto que Pandas pueda leer como un archivo
archivo_limpio = io.StringIO('\n'.join(lineas_limpias))

# Carga el DataFrame usando el archivo preprocesado, especificando los nombres de las columnas y sin encabezado.
# Se quita `index_col=0` para tratar a 'ID' como una columna común en lugar del índice del DataFrame.
# Se usa `on_bad_lines='skip'` para omitir filas mal formateadas, y `dtype=str` para evitar advertencias de tipos mixtos.
df = pd.read_csv(archivo_limpio, header=None, names=nombres_columnas, on_bad_lines='skip', dtype=str)

# La primera fila sigue siendo el encabezado del CSV original, por lo que la eliminamos.
df = df.iloc[1:].copy()

# Clean 'Mortality Y / N' column as requested by the user
df["Mortality Y / N"] = df["Mortality Y / N"].replace('17/09/2017 00:00:00', np.nan)
df = df.dropna(subset=['Mortality Y / N'])

# Muestra las primeras filas para verificar el resultado
df.head()

"""Algunas variables:

AGE: Permite ver qué grupos etarios usan más el sistema.

SEX: Diferencias de género en acceso y tipo de procedimiento.

CATEGORY_NAME / SURGERY: Las patologías más frecuentes sistema público.

PREAUTH_AMT vs CLAIM_AMOUNT: La diferencia entre ambas puede indicar ineficiencias o irregularidades.

HOSP_TYPE (G vs C): ¿Los hospitales privados cobran más? ¿Tienen diferente mortalidad?

DISTRICT_NAME: Análisis de equidad, ¿hay distritos con menos acceso o más mortalidad?

Mortality Y / NC: Variable clave de resultado en salud. ¿Qué factores se asocian con mortalidad?

SURGERY_DATE / DISCHARGE_DATE: Permiten calcular días de internación, analizar tendencias en el tiempo.

CASTE_NAME: Variable de equidad social: ¿acceden por igual todos los grupos?
"""

# Filas y columnas del dataset
print(f"Filas: {df.shape[0]:,} | Columnas: {df.shape[1]}")
print()

# Nombres de las columnas
print("Columnas disponibles:")
print(df.columns.tolist())
print()

# Tipo de dato de cada columna (int64 = número, object = texto/categoría)
print("Tipos de datos:")
print(df.dtypes)

"""Encontramos 24 variables de distintos tipos:

Numéricas: AGE, PREAUTH_AMT, CLAIM_AMOUNT

Categóricas: SEX, CASTE_NAME, CATEGORY_NAME, SURGERY, HOSP_TYPE, Mortality Y / N

Geográficas: VILLAGE, MANDAL_NAME, DISTRICT_NAME, HOSP_LOCATION, HOSP_DISTRICT

Temporales: PREAUTH_DATE, CLAIM_DATE, SURGERY_DATE, DISCHARGE_DATE, MORTALITY_DATE

Identificadoras/redundantes: la primera columna (índice), SURGERY_CODE, CATEGORY_CODE, SRC_REGISTRATION
"""

# Contamos cuántos valores faltantes hay por columna
nulos = df.isnull().sum()
porcentaje = (nulos / len(df) * 100).round(2)

# Armamos una tabla resumen más clara
resumen_nulos = pd.DataFrame({
    "Valores nulos": nulos,
    "Porcentaje (%)": porcentaje
}).sort_values("Valores nulos", ascending=False)

print("Valores faltantes por columna:")
print(resumen_nulos[resumen_nulos["Valores nulos"] > 0])

"""MORTALITY_DATE: tiene 96,29% de valores vacíos, asumimos que de paicientes que no fallecieron.

DISCHARGE_DATE: tiene pocos nulos, pero puede indicar casos donde el paciente no tuvo alta registrada.
"""

# Separamos las columnas según su tipo de dato
variables_numericas = df.select_dtypes(include=["int64", "float64"]).columns.tolist()
variables_categoricas = df.select_dtypes(include=["object"]).columns.tolist()

print("Variables NUMÉRICAS:", variables_numericas)
print()
print("Variables CATEGÓRICAS (texto):", variables_categoricas)
print()

# Para las categóricas, veamos cuántas categorías únicas tiene cada una
print("Cantidad de categorías únicas por variable categórica:")
for col in variables_categoricas:
    n = df[col].nunique()
    print(f"  {col}: {n} valores únicos")

df["AGE"] = pd.to_numeric(df["AGE"], errors='coerce')

# Gráfico 1: Distribución de edades
plt.figure(figsize=(8, 5))
sns.histplot(df["AGE"].dropna(), bins=30, kde=True, color="steelblue")
plt.title("Distribución de Edades de los Pacientes")
plt.xlabel("Edad")
plt.ylabel("Cantidad de pacientes")
plt.tight_layout()
add_chart(plt.gcf())

"""La mayoría de los pacientes está concentrada entre los 40 y 60 años, mientras que hay menos pacientes jóvenes y muy pocos mayores de 80.
También aparece un grupo pequeño de pacientes de edad muy baja (0-5 años), probablemente asociado a pediatría.

El sistema de salud parece es utilizado principalmente por adultos y adultos mayores, asumimos por las enfermedades complejas o cirugías que son más frecuentes en edades medias y avanzadas.
"""

#  Gráfico 2: Distribución por sexo
plt.figure(figsize=(7, 4))
df["SEX"].value_counts().plot(kind="bar", color=["steelblue", "salmon", "skyblue", "lightcoral"])
plt.title("Distribución por Sexo")
plt.xlabel("Sexo")
plt.ylabel("Cantidad de pacientes")
plt.xticks(rotation=15)
plt.tight_layout()
add_chart(plt.gcf())

"""Vemos que existen categorías duplicadas: Male y MALE, Female y FEMALE

También aparecen categorías separadas para niños: Male(Child), Female(Child)

El dataset tiene problemas de estandarización de datos, la diferencia entre mayúsculas y minúsculas genera categorías separadas aunque representan lo mismo.
"""

# Limpiamos la variable SEX
# Verificamos cómo está antes para comparar
print("Antes de limpiar")
print(df["SEX"].value_counts())
print()

# estandarizamos (minúsculas + sin espacios extra)
df["SEX_clean"] = df["SEX"].str.strip().str.lower()

#  mapeamos a las categorías finales
mapeo_sexo = {
    "male":           "Male",
    "female":         "Female",
    "male(child)":    "Male (Child)",
    "female(child)":  "Female (Child)"
}
df["SEX_clean"] = df["SEX_clean"].map(mapeo_sexo)

# columna auxiliar para separar adultos de menores
df["ES_MENOR"] = df["SEX_clean"].str.contains("Child").map({True: "Menor", False: "Adulto"})

# Verificamos el resultado
print("Después de limpiar")
print(df["SEX_clean"].value_counts())
print()
print("Nulos en SEX_clean", df["SEX_clean"].isnull().sum())
print()
print("Columna ES_MENOR:")
print(df["ES_MENOR"].value_counts())

#  Gráfico 2: Distribución por sexo
fig, ax = plt.subplots(figsize=(8, 5))

valores = df["SEX_clean"].value_counts()
colores = ["steelblue", "salmon", "skyblue", "lightcoral"]
bars = ax.bar(valores.index, valores.values, color=colores, edgecolor="white")

# Número absoluto Y porcentaje encima de cada barra
total = valores.sum()
for bar, val in zip(bars, valores.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1500,
            f"{val:,}\n({val/total*100:.1f}%)",
            ha="center", va="bottom", fontsize=9)

ax.set_title("Distribución de Pacientes por Sexo")
ax.set_xlabel("Sexo")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores.max() * 1.18)  # espacio para las etiquetas
plt.xticks(rotation=15)
plt.tight_layout()
add_chart(plt.gcf())

"""Se observa que los pacientes masculinos son más que los femeninos
(incluso en niños). Esto puede indicar menor acceso de las mujeres al sistema,
o que los hombres tienen mayor prevalencia de las enfermedades cubiertas.
"""

# Gráfico de Distribución por Sexo para la Casta BC
df_bc = df[df["CASTE_NAME"] == "BC"].copy()

fig, ax = plt.subplots(figsize=(8, 5))

valores_bc = df_bc["SEX_clean"].value_counts()
# Mantener la paleta de colores original, ajustando si es necesario según las categorías presentes
colores_bc = {
    "Male": "steelblue",
    "Female": "salmon",
    "Male (Child)": "skyblue",
    "Female (Child)": "lightcoral"
}

# Asegurarse de que el orden de los colores coincida con el orden de los valores
bar_colors = [colores_bc.get(sex, 'gray') for sex in valores_bc.index]

bars = ax.bar(valores_bc.index, valores_bc.values, color=bar_colors, edgecolor="white")

# Número absoluto Y porcentaje encima de cada barra
total_bc = valores_bc.sum()
for bar, val in zip(bars, valores_bc.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1500, # Ajustar este valor para la posición vertical de la etiqueta
            f"{val:,}\n({val/total_bc*100:.1f}%)",
            ha="center", va="bottom", fontsize=9)

ax.set_title("Distribución de Pacientes por Sexo en Casta BC")
ax.set_xlabel("Sexo")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores_bc.max() * 1.18)  # espacio para las etiquetas
plt.xticks(rotation=15)
plt.tight_layout()
add_chart(plt.gcf())

# Gráfico de Distribución por Sexo para la Casta OC
df_oc = df[df["CASTE_NAME"] == "OC"].copy()

fig, ax = plt.subplots(figsize=(8, 5))

valores_oc = df_oc["SEX_clean"].value_counts()
# Mantener la paleta de colores original, ajustando si es necesario según las categorías presentes
colores_oc = {
    "Male": "steelblue",
    "Female": "salmon",
    "Male (Child)": "skyblue",
    "Female (Child)": "lightcoral"
}

# Asegurarse de que el orden de los colores coincida con el orden de los valores
bar_colors = [colores_oc.get(sex, 'gray') for sex in valores_oc.index]

bars = ax.bar(valores_oc.index, valores_oc.values, color=bar_colors, edgecolor="white")

# Número absoluto Y porcentaje encima de cada barra
total_oc = valores_oc.sum()
for bar, val in zip(bars, valores_oc.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1500, # Ajustar este valor para la posición vertical de la etiqueta
            f"{val:,}\n({val/total_oc*100:.1f}%)",
            ha="center", va="bottom", fontsize=9)

ax.set_title("Distribución de Pacientes por Sexo en Casta OC")
ax.set_xlabel("Sexo")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores_bc.max() * 1.18)  # espacio para las etiquetas
plt.xticks(rotation=15)
plt.tight_layout()
add_chart(plt.gcf())

# Gráfico 3: Categorías médicas más frecuentes
plt.figure(figsize=(10, 5))
df["CATEGORY_NAME"].value_counts().head(10).plot(kind="barh", color="teal")
plt.title("Categorías médicas más frecuentes ")
plt.xlabel("Casos")
plt.ylabel("Categoría médica")
plt.gca().invert_yaxis()  # Para que el más frecuente quede arriba
plt.tight_layout()
add_chart(plt.gcf())

"""Las categorías más frecuentes son: Nefrología, Cirugía cardíaca/cardiotorácica,Pediatria, Neurología, Cardiologia, y Politrauma."""

# Gráfico 4: Tipo de hospital (G = Gobierno, C = Corporativo/Privado)
plt.figure(figsize=(6, 4))
df["HOSP_TYPE"].value_counts().plot(kind="bar", color=["steelblue", "salmon"])
plt.title("Tipo de Hospital")
plt.xlabel("Tipo")
plt.ylabel("Cantidad")
plt.xticks(rotation=0)
plt.tight_layout()
add_chart(plt.gcf())

print(df["Mortality Y / N"].value_counts(dropna=False))
print(f"Valores únicos en 'Mortality Y / N': {df['Mortality Y / N'].unique()}")

# Gráfico 5: Mortalidad
plt.figure(figsize=(5, 4))
df["Mortality Y / N"].value_counts().plot(kind="bar", color=["green", "red"])
plt.title("Mortalidad de los pacientes")
plt.xlabel("¿Falleció?")
plt.ylabel("Cantidad")
plt.xticks(rotation=0)
plt.tight_layout()
add_chart(plt.gcf())

"""El gráfico muestra una diferencia enorme entre pacientes que fallecieron y los que no. La mortalidad es muy baja respecto al total de casos.

La mayoría de los procedimientos tuvieron resultados favorables, también hay que considerar que algunas intervenciones sdeben tratamientos programados y no necesariamente casos críticos.
"""

# Gráfico 6: Distribución de montos cobrados
plt.figure(figsize=(10, 4))
sns.histplot(df["CLAIM_AMOUNT"], bins=40, kde=True, color="darkorange")
plt.title("Distribución del Monto Cobrado")
plt.xlabel("Monto (Rupias)")
plt.ylabel("Frecuencia")
plt.tight_layout()
add_chart(plt.gcf())

"""Este gráfico  muestra una distribución claramente asimétrica hacia la derecha.

La mayoría de los tratamientos tienen montos relativamente bajos o medios, hay pocos casos extremadamente caros.

Esto puede ser porque el sistema concentra muchos tratamientos de costo moderado. Probablemente las cirugías complejas (oncología, cardíacas, nefrología, etc) expliquen ciertos montos extremos.
"""

# Gráfico 7: Castas
fig, ax = plt.subplots(figsize=(10, 5))

datos = df["CASTE_NAME"].value_counts()
total = datos.sum()

bars = ax.barh(datos.index[::-1], datos.values[::-1],
               color="teal", edgecolor="white")

# Número absoluto + porcentaje al final de cada barra
for bar, val in zip(bars, datos.values[::-1]):
    ax.text(bar.get_width() + 500,
            bar.get_y() + bar.get_height() / 2,
            f"{val:,}  ({val/total*100:.1f}%)",
            va="center", fontsize=9)

ax.set_title("Distribución de Pacientes por Casta")
ax.set_xlabel("Cantidad de casos")
ax.set_ylabel("Casta")
ax.set_xlim(0, datos.max() * 1.22)
plt.tight_layout()
add_chart(plt.gcf())

""" El sistema está diseñado para ayudar a personas que sufrieron discriminación histórica en la India.

La casta (CASTE_NAME) es un sistema social de nacimiento muy antiguo en la India, que divide a las personas en grupos sociales fijos. Determina tradicionalmente tu estatus social y tu oficio. No se puede cambiar; naces y mueres en la misma casta.

Las reservas son un sistema de cuotas obligatorias, donde el gobierno de la India aparta un porcentaje de lugares exclusivamente para las castas más bajas (SC, ST, OBC).Estas reservas se aplican principalmente en educación y empleo, para asegurar que las personas de castas bajas tengan acceso a la educación y a buenos trabajos.

* BC (Backward Classes): Clases Atrás en el Desarrollo. Castas intermedias. Sufren de cierta desventaja económica o educativa, pero menos extrema que SC o ST.
* OC (Open Category): Categoría General. Personas de castas altas o privilegiadas. Tradicionalmente tienen mejor nivel socioeconómico y acceso a salud privada.
* Minorias: personas que profesan otras religiones (no hinduista):musulmanes, cristianos, budistas, etc.
* SC (Scheduled Castes): Castas Protegidas (históricamente llamados Dalits o "intocables"). Comunidades que han sufrido discriminación extrema y pobreza severa por siglos.
* ST (Scheduled Tribes): Tribus Protegidas. Comunidades indígenas originarias de la India. Suelen vivir en zonas rurales, montañosas o boscosas aisladas, con muy poco acceso a hospitales.
"""

# Gráfico 8: Edad según Casta
# Usamos un boxplot: muestra el rango de edades, el promedio y los valores extremos

plt.figure(figsize=(10, 5))
orden_castas = ["BC", "OC", "SC", "Minorities", "ST", "Others"]

sns.boxplot(data=df, x="CASTE_NAME", y="AGE",
            order=orden_castas,
            palette="Set2")

plt.title("Distribución de Edad según Casta")
plt.xlabel("Casta")
plt.ylabel("Edad")
plt.tight_layout()
add_chart(plt.gcf())

# Complementamos con la edad promedio por casta (más fácil de leer)
print("Edad promedio por casta:")
print(df.groupby("CASTE_NAME")["AGE"].mean().round(1).sort_values(ascending=False))

"""Las castas SC y ST tienden a tener pacientes más jóvenes en promedio.
Esto puede interpretarse de dos formas:
- Las poblaciones SC/ST tienen una estructura etaria más joven (más común
  en comunidades rurales con alta natalidad).
- O bien, acceden al sistema con enfermedades más graves a edades más
  tempranas, posiblemente por menor acceso preventivo durante toda su vida.

OC (casta alta) tiende a tener pacientes de mayor edad, lo que puede
reflejar que acceden a atención preventiva y llegan al sistema más tarde,
cuando ya son adultos mayores.
"""

# Grafico 9: Casta por Sexo
adultos = df[df["SEX_clean"].isin(["Male", "Female"])].copy()
casta_sexo = (adultos.groupby(["CASTE_NAME", "SEX_clean"])
                      .size()
                      .unstack(fill_value=0))

casta_sexo_pct = casta_sexo.div(casta_sexo.sum(axis=1), axis=0) * 100

print("Porcentaje de hombres y mujeres por casta:")
print(casta_sexo_pct.round(1))
print()

casta_sexo_pct.reindex(["BC", "OC", "SC", "Minorities", "ST", "Others"]).plot(
    kind="bar",
    stacked=False,
    color=["salmon","steelblue"],
    figsize=(10, 5),
    edgecolor="white",
    width=0.7
)

plt.title("Distribución de Sexo dentro de cada Casta (% adultos)")
plt.xlabel("Casta")
plt.ylabel("Porcentaje (%)")
plt.xticks(rotation=15)
plt.legend(title="Sexo", bbox_to_anchor=(1.01, 1), loc="upper left")

# Agregamos el % encima de cada barra
ax = plt.gca()
for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f}%",
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha="center", va="bottom", fontsize=8)

plt.tight_layout()
add_chart(plt.gcf())

"""La brecha es consistente en todas las castas (~65% hombres / ~35% mujeres), pero "Others" rompe completamente el patrón: 84.3% hombres y solo 15.7% mujeres. Con n=56 hay que tomarlo con cautela, pero es llamativo. Podría indicar que esa categoría agrupa casos atípicos o registros con errores de clasificación."""

# Grafico 10: Mortalidad según Casta y tamaño de población
mortalidad_casta = (df.groupby("CASTE_NAME")["Mortality Y / N"]
                      .value_counts(normalize=True)
                      .unstack(fill_value=0) * 100)

# Contamos cuántos pacientes hay por casta (n)
poblacion_casta = df["CASTE_NAME"].value_counts()

orden = ["BC", "OC", "SC", "Minorities", "ST", "Others"]

print("Tasa de mortalidad por casta (%):")
print(mortalidad_casta.round(2))
print()
print("Cantidad de pacientes por casta:")
print(poblacion_casta.reindex(orden))

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# Gráfico superior: tasa de mortalidad
valores_mort = mortalidad_casta["YES"].reindex(orden)
bars1 = ax1.bar(orden, valores_mort,
                color="#c94444", edgecolor="white", width=0.6)

ax1.set_title("Tasa de Mortalidad por Casta (%)", fontsize=13)
ax1.set_ylabel("% de pacientes fallecidos")
ax1.set_xlabel("")

# Etiquetas encima de cada barra
for bar, val in zip(bars1, valores_mort):
    ax1.text(bar.get_x() + bar.get_width() / 2,
             val + 0.03,
             f"{val:.2f}%",
             ha="center", va="bottom", fontsize=10)

# Gráfico inferior: cantidad de pacientes por casta
valores_pob = poblacion_casta.reindex(orden)
bars2 = ax2.bar(orden, valores_pob,
                color="steelblue", edgecolor="white", width=0.6)

ax2.set_title("Cantidad de Pacientes por Casta (n)", fontsize=13)
ax2.set_ylabel("Cantidad de pacientes")
ax2.set_xlabel("Casta")

# Etiquetas encima de cada barra con el n exacto
for bar, val in zip(bars2, valores_pob):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             val + 500,
             f"{val:,}",       # formato con coma de miles
             ha="center", va="bottom", fontsize=10)

plt.tight_layout(pad=3)
add_chart(plt.gcf())

"""Others tiene 2,44% con el segundo número de pacientes más bajo.
Hay que ver condiciones de vida, etc.
"""

# Gráfico 11: Mortalidad por casta y sexo

# creamos grupos de edad con rangos clínicamente usados
bins  = [0, 17, 34, 49, 64, 110]
labels = ["0–17", "18–34", "35–49", "50–64", "65+"]

df["GRUPO_EDAD"] = pd.cut(df["AGE"], bins=bins, labels=labels, right=True)

# filtramos solo adultos con sexo claro (Male / Female)
df_filtrado = df[df["SEX_clean"].isin(["Male", "Female"])].copy()

orden_castas = ["BC", "OC", "SC", "Minorities", "ST", "Others"]
orden_edad   = ["0–17", "18–34", "35–49", "50–64", "65+"]
colores_sexo = {"Male": "steelblue", "Female": "salmon"}

# Gráfico: una fila por casta, dentro de cada casta barras por grupo edad, cada barra dividida por sexo (agrupadas)
fig, axes = plt.subplots(3, 2, figsize=(14, 14))
axes = axes.flatten()  # para iterar fácil

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]
    subset = df_filtrado[df_filtrado["CASTE_NAME"] == casta]

    # Tasa de mortalidad por grupo de edad y sexo
    mort = (subset.groupby(["GRUPO_EDAD", "SEX_clean"])["Mortality Y / N"]
                  .apply(lambda x: (x == "YES").sum() / len(x) * 100)
                  .unstack(fill_value=0)
                  .reindex(orden_edad))

    # n por grupo (para mostrarlo en el título de cada subgráfico)
    n_casta = len(subset)

    # Barras agrupadas por sexo dentro de cada grupo de edad
    x = range(len(orden_edad))
    ancho = 0.35

    for i, sexo in enumerate(["Male", "Female"]):
        if sexo in mort.columns:
            valores = mort[sexo].fillna(0)
            bars = ax.bar(
                [xi + i * ancho for xi in x],
                valores,
                width=ancho,
                label=sexo,
                color=colores_sexo[sexo],
                edgecolor="white"
            )
            # Etiquetas encima de cada barra (solo si > 0)
            for bar, val in zip(bars, valores):
                if val > 0:
                    ax.text(bar.get_x() + bar.get_width() / 2,
                            val + 0.05,
                            f"{val:.1f}%",
                            ha="center", va="bottom", fontsize=7)

    ax.set_title(f"{casta}  (n = {n_casta:,})", fontsize=11, fontweight="bold")
    ax.set_ylabel("% mortalidad")
    ax.set_xlabel("Grupo de edad")
    ax.set_xticks([xi + ancho / 2 for xi in x])
    ax.set_xticklabels(orden_edad)
    ax.legend(title="Sexo", fontsize=8)

plt.suptitle("Mortalidad por Casta, Grupo de Edad y Sexo", fontsize=14, fontweight="bold", y=1.01)
plt.tight_layout()
add_chart(plt.gcf())

"""En BC, SC y OC la mortalidad sube ordenadamente con la edad, como se espera biológicamente.

En Minorities, las mujeres tienen mortalidad consistentemente más alta que los hombres en todos los grupos de edad — especialmente en 65+ (8.7% mujeres vs 7.0% hombres).

ST es el caso más llamativo: los hombres de 50–64 tienen 11.6% de mortalidad, el valor más alto de todo el análisis. Y en 65+ baja a 9.8%, lo cual puede parecer raro pero puede explicarse porque los más frágiles ya murieron antes (sesgo de supervivencia).

En ST las mujeres jóvenes (18–34) tienen 7.4% de mortalidad — muy alto para ese grupo etario.

## Ampliado
"""

# Definimos los nuevos grupos de edad para el rango de 0 a 34 años
bins_jovenes = [0, 5, 10, 15, 20, 25, 30, 35]
labels_jovenes = ['0-4', '5-9', '10-14', '15-19', '20-24', '25-29', '30-34']

df['GRUPO_EDAD_JOVEN'] = pd.cut(df['AGE'], bins=bins_jovenes, labels=labels_jovenes, right=False)

# Filtramos solo a los pacientes dentro de este rango de edad y con sexo limpio (Male/Female)
df_jovenes = df[df['SEX_clean'].isin(['Male', 'Female']) & df['AGE'].between(0, 34)].copy()

orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']
orden_edad_joven = labels_jovenes # Usamos los nuevos labels de edad
colores_sexo = {'Male': 'steelblue', 'Female': 'salmon'}

# Creamos una figura con subplots para cada casta
fig, axes = plt.subplots(3, 2, figsize=(14, 14))
axes = axes.flatten()

plt.suptitle('Mortalidad por Casta, Grupo de Edad y Sexo (0-34 años)', fontsize=14, fontweight='bold', y=1.02)

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]
    subset = df_jovenes[df_jovenes['CASTE_NAME'] == casta]

    # Calculamos la tasa de mortalidad por grupo de edad y sexo
    mort = (subset.groupby(['GRUPO_EDAD_JOVEN', 'SEX_clean'])['Mortality Y / N']
                  .apply(lambda x: (x == 'YES').sum() / len(x) * 100)
                  .unstack(fill_value=0)
                  .reindex(orden_edad_joven))

    # Contamos el número de pacientes por casta (n) para el título
    n_casta = len(subset)

    # Barras agrupadas por sexo dentro de cada grupo de edad
    x = range(len(orden_edad_joven))
    ancho = 0.35

    for i, sexo in enumerate(['Male', 'Female']):
        if sexo in mort.columns:
            valores = mort[sexo].fillna(0)
            bars = ax.bar(
                [xi + i * ancho for xi in x],
                valores,
                width=ancho,
                label=sexo,
                color=colores_sexo[sexo],
                edgecolor='white'
            )
            # Etiquetas encima de cada barra (solo si > 0)
            for bar, val in zip(bars, valores):
                if val > 0:
                    ax.text(bar.get_x() + bar.get_width() / 2,
                            val + 0.05,
                            f'{val:.1f}%',
                            ha='center', va='bottom', fontsize=7)

    ax.set_title(f'{casta} (n = {n_casta:,})', fontsize=11, fontweight='bold')
    ax.set_ylabel('% mortalidad')
    ax.set_xlabel('Grupo de edad')
    ax.set_xticks([xi + ancho / 2 for xi in x])
    ax.set_xticklabels(orden_edad_joven, rotation=45, ha='right')
    ax.legend(title='Sexo', fontsize=8)
    ax.set_ylim(0, mort.max().max() * 1.2 if not mort.empty else 1)

plt.tight_layout()
add_chart(plt.gcf())

"""## Gráfico 11.1: Mortalidad por Casta y Sexo (0-17 años, solo niños)"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Definimos los nuevos grupos de edad para el rango de 0 a 17 años con bins de 5 años
bins_ninos = [0, 5, 10, 15, 18] # El último valor es el límite superior exclusivo
labels_ninos = ['0-4', '5-9', '10-14', '15-17']

df['GRUPO_EDAD_NINOS'] = pd.cut(df['AGE'], bins=bins_ninos, labels=labels_ninos, right=False)

# Filtramos solo a los pacientes dentro de este rango de edad y con sexo 'Child'
df_ninos = df[
    df['SEX_clean'].isin(['Male (Child)', 'Female (Child)']) &
    df['AGE'].between(0, 17, inclusive='both') # Aseguramos inclusión de 17
].copy()

orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']
orden_edad_ninos = labels_ninos # Usamos los nuevos labels de edad
colores_sexo_ninos = {'Male (Child)': 'skyblue', 'Female (Child)': 'lightcoral'}

# Creamos una figura con subplots para cada casta
fig, axes = plt.subplots(3, 2, figsize=(14, 14))
axes = axes.flatten()

plt.suptitle('Gráfico 11.1: Mortalidad por Casta, Grupo de Edad y Sexo (0-17 años, solo niños)',
             fontsize=14, fontweight='bold', y=1.02)

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]
    subset = df_ninos[df_ninos['CASTE_NAME'] == casta]

    # Calculamos la tasa de mortalidad por grupo de edad y sexo
    mort_ninos = (subset.groupby(['GRUPO_EDAD_NINOS', 'SEX_clean'])['Mortality Y / N']
                  .apply(lambda x: (x == 'YES').sum() / len(x) * 100)
                  .unstack(fill_value=0)
                  .reindex(orden_edad_ninos))

    # Contamos el número de pacientes por casta (n) para el título
    n_casta = len(subset)

    # Barras agrupadas por sexo dentro de cada grupo de edad
    x = range(len(orden_edad_ninos))
    ancho = 0.35

    # Definir las categorías de sexo a plotear para niños
    sex_categories_to_plot_ninos = ['Male (Child)', 'Female (Child)']

    for i, sexo in enumerate(sex_categories_to_plot_ninos):
        if sexo in mort_ninos.columns:
            valores = mort_ninos[sexo].fillna(0)
            bars = ax.bar(
                [xi + i * ancho for xi in x],
                valores,
                width=ancho,
                label=sexo,
                color=colores_sexo_ninos[sexo],
                edgecolor='white'
            )
            # Etiquetas encima de cada barra (solo si > 0)
            for bar, val in zip(bars, valores):
                if val > 0:
                    ax.text(bar.get_x() + bar.get_width() / 2,
                            val + 0.05,
                            f'{val:.1f}%',
                            ha='center', va='bottom', fontsize=7)

    ax.set_title(f'{casta} (n = {n_casta:,})', fontsize=11, fontweight='bold')
    ax.set_ylabel('% mortalidad')
    ax.set_xlabel('Grupo de edad')
    ax.set_xticks([xi + ancho / 2 for xi in x])
    ax.set_xticklabels(orden_edad_ninos, rotation=45, ha='right')
    ax.legend(title='Sexo', fontsize=8)
    ax.set_ylim(0, mort_ninos.max().max() * 1.2 if not mort_ninos.empty else 1)

plt.tight_layout()
add_chart(plt.gcf())

"""## Gráfico 11.2: Top 8 Categorías Médicas con Mortalidad en Mujeres (15-34 años) por Casta

Este gráfico se centra en las causas de mortalidad en un grupo demográfico específico: mujeres jóvenes (15-34 años). Analizaremos las 8 categorías médicas donde se registran más fallecimientos dentro de este grupo, desglosadas por casta.
"""

# 1. Filtramos el dataset para mujeres de 15 a 34 años
grupos_edad_mujeres_15_34 = ['15-19', '20-24', '25-29', '30-34']

df_mujeres_15_34 = df[
    (df['SEX_clean'] == 'Female') &
    (df['GRUPO_EDAD_JOVEN'].isin(grupos_edad_mujeres_15_34))
].copy()

# 2. Identificamos las top 8 CATEGORY_NAME con más fallecimientos en este grupo
mortality_counts_15_34_female = df_mujeres_15_34[
    df_mujeres_15_34['Mortality Y / N'] == 'YES'
]['CATEGORY_NAME'].value_counts()

top_8_categorias_mort = mortality_counts_15_34_female.head(8).index.tolist()

# Asegurarse de que haya al menos una categoría si el DataFrame no está vacío
if not top_8_categorias_mort and not df_mujeres_15_34.empty:
    print("Advertencia: No se encontraron fallecimientos en mujeres de 15-34 años para determinar las top 8 categorías.")
    # En este caso, podríamos optar por usar las top 8 categorías generales o mostrar un gráfico vacío.
    # Por ahora, si no hay fallecimientos, el gráfico se adaptará para mostrar 0%.

# 3. Calculamos la tasa de mortalidad para estas top 8 categorías, por casta
orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']
mort_rates_por_cat_caste = {}

for casta in orden_castas:
    subset_caste = df_mujeres_15_34[df_mujeres_15_34['CASTE_NAME'] == casta]

    # Total de pacientes (mujeres 15-34) por categoría en esta casta
    total_patients_per_cat = subset_caste['CATEGORY_NAME'].value_counts()

    # Pacientes fallecidos (mujeres 15-34) por categoría en esta casta
    deceased_patients_per_cat = subset_caste[
        subset_caste['Mortality Y / N'] == 'YES'
    ]['CATEGORY_NAME'].value_counts()

    # Calcular la tasa de mortalidad (puede ser NaN si no hay pacientes en la categoría)
    mortality_rate_series = (deceased_patients_per_cat / total_patients_per_cat) * 100
    mortality_rate_series = mortality_rate_series.fillna(0) # Reemplazar NaN con 0

    # Reindexar para asegurar que todas las top 8 categorías estén presentes
    # y llenar con 0 si una categoría no tiene casos en esta casta/demografía
    mort_rates_por_cat_caste[casta] = mortality_rate_series.reindex(top_8_categorias_mort, fill_value=0)

df_mort_rates_mujeres_15_34 = pd.DataFrame(mort_rates_por_cat_caste)

# 4. Trazar los resultados
fig, axes = plt.subplots(3, 2, figsize=(16, 18))
axes = axes.flatten()

plt.suptitle('Top 8 Categorías con Mortalidad en Mujeres (15-34 años) por Casta',
             fontsize=16, fontweight='bold', y=1.02)

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]

    # Obtener el número total de pacientes (mujeres 15-34) para el título
    n_casta = len(df_mujeres_15_34[df_mujeres_15_34['CASTE_NAME'] == casta])

    # Obtener los datos de mortalidad para la casta actual
    # Ordenar de mayor a menor para que las categorías con más mortalidad estén arriba
    mort_data = df_mort_rates_mujeres_15_34[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data.empty and mort_data.max() > 0:
        bars = ax.barh(mort_data.index, mort_data.values, color='darkred', edgecolor='white')

        # Añadir etiquetas de porcentaje al final de cada barra
        for bar in bars:
            width = bar.get_width()
            if width > 0.05: # Solo si el valor es significativo para mostrar
                ax.text(width + 0.5, bar.get_y() + bar.get_height() / 2,
                        f'{width:.1f}%',
                        va='center', ha='left', fontsize=8)
        max_xlim = mort_data.max() * 1.3 # Extender un poco para las etiquetas
    else:
        # Si no hay datos o la mortalidad es 0, asegurarse de que el gráfico se muestre correctamente
        ax.text(0.5, 0.5, 'Sin datos de mortalidad en esta casta',
                horizontalalignment='center', verticalalignment='center',
                transform=ax.transAxes, fontsize=10, color='gray')
        max_xlim = 1 # Establecer un límite base si no hay datos

    ax.set_title(f'{casta} (n = {n_casta:,})', fontsize=11, fontweight='bold')
    ax.set_xlabel('% Mortalidad')
    ax.set_ylabel('Categoría Médica')
    ax.set_xlim(0, max_xlim)
    ax.tick_params(axis='y', labelsize=9)

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Ajustar layout para hacer espacio para el suptitle
add_chart(plt.gcf())

"""## Gráfico 11.2.1: Top 8 Categorías Médicas con Mortalidad en Niñas (0-17 años) por Casta"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Definimos los nuevos grupos de edad para el rango de 0 a 17 años con bins de 5 años
bins_ninas = [0, 5, 10, 15, 18] # El último valor es el límite superior exclusivo
labels_ninas = ['0-4', '5-9', '10-14', '15-17']

df['GRUPO_EDAD_NINAS'] = pd.cut(df['AGE'], bins=bins_ninas, labels=labels_ninas, right=False)

# 1. Filtramos el dataset para niñas de 0 a 17 años
df_ninas_0_17 = df[
    (df['SEX_clean'] == 'Female (Child)') &
    (df['AGE'].between(0, 17, inclusive='both'))
].copy()

# 2. Identificamos las top 8 CATEGORY_NAME con más fallecimientos en este grupo
mortality_counts_ninas_0_17 = df_ninas_0_17[
    df_ninas_0_17['Mortality Y / N'] == 'YES'
]['CATEGORY_NAME'].value_counts()

top_8_categorias_ninas_mort = mortality_counts_ninas_0_17.head(8).index.tolist()

# Asegurarse de que haya al menos una categoría si el DataFrame no está vacío
if not top_8_categorias_ninas_mort and not df_ninas_0_17.empty:
    print("Advertencia: No se encontraron fallecimientos en niñas de 0-17 años para determinar las top 8 categorías.")

# 3. Calculamos la tasa de mortalidad para estas top 8 categorías, por casta
orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']
mort_rates_por_cat_caste_ninas = {}

for casta in orden_castas:
    subset_caste = df_ninas_0_17[df_ninas_0_17['CASTE_NAME'] == casta]

    # Total de pacientes (niñas 0-17) por categoría en esta casta
    total_patients_per_cat = subset_caste['CATEGORY_NAME'].value_counts()

    # Pacientes fallecidos (niñas 0-17) por categoría en esta casta
    deceased_patients_per_cat = subset_caste[
        subset_caste['Mortality Y / N'] == 'YES'
    ]['CATEGORY_NAME'].value_counts()

    # Calcular la tasa de mortalidad
    mortality_rate_series = (deceased_patients_per_cat / total_patients_per_cat) * 100
    mortality_rate_series = mortality_rate_series.fillna(0) # Reemplazar NaN con 0

    # Reindexar para asegurar que todas las top 8 categorías estén presentes
    # y llenar con 0 si una categoría no tiene casos en esta casta/demografía
    mort_rates_por_cat_caste_ninas[casta] = mortality_rate_series.reindex(top_8_categorias_ninas_mort, fill_value=0)

df_mort_rates_ninas_0_17 = pd.DataFrame(mort_rates_por_cat_caste_ninas)

# 4. Trazar los resultados
fig, axes = plt.subplots(3, 2, figsize=(16, 18))
axes = axes.flatten()

plt.suptitle('Gráfico 11.2.1: Top 8 Categorías Médicas con Mortalidad en Niñas (0-17 años) por Casta',
             fontsize=16, fontweight='bold', y=1.02)

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]

    # Obtener el número total de pacientes (niñas 0-17) para el título
    n_casta = len(df_ninas_0_17[df_ninas_0_17['CASTE_NAME'] == casta])

    # Obtener los datos de mortalidad para la casta actual
    mort_data = df_mort_rates_ninas_0_17[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data.empty and mort_data.max() > 0:
        bars = ax.barh(mort_data.index, mort_data.values, color='darkred', edgecolor='white')

        # Añadir etiquetas de porcentaje al final de cada barra
        for bar in bars:
            width = bar.get_width()
            if width > 0.05: # Solo si el valor es significativo para mostrar
                ax.text(width + 0.5, bar.get_y() + bar.get_height() / 2,
                        f'{width:.1f}%',
                        va='center', ha='left', fontsize=8)
        max_xlim = mort_data.max() * 1.3 # Extender un poco para las etiquetas
    else:
        # Si no hay datos o la mortalidad es 0, asegurarse de que el gráfico se muestre correctamente
        ax.text(0.5, 0.5, 'Sin datos de mortalidad en esta casta',
                horizontalalignment='center', verticalalignment='center',
                transform=ax.transAxes, fontsize=10, color='gray')
        max_xlim = 1 # Establecer un límite base si no hay datos

    ax.set_title(f'{casta} (n = {n_casta:,})', fontsize=11, fontweight='bold')
    ax.set_xlabel('% Mortalidad')
    ax.set_ylabel('Categoría Médica')
    ax.set_xlim(0, max_xlim)
    ax.tick_params(axis='y', labelsize=9)

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Ajustar layout para hacer espacio para el suptitle
add_chart(plt.gcf())

"""## Gráfico 11.4: Top 8 Cirugías con Mortalidad (%, y n) en Mujeres (15-34 años) por Casta

Este gráfico amplía el análisis anterior, mostrando no solo el porcentaje de mortalidad sino también el número absoluto de fallecimientos para cada una de las 8 cirugías más mortales en mujeres de 15 a 34 años, desglosado por casta. Esto ayuda a comprender si un alto porcentaje se debe a una alta letalidad real o a un número muy reducido de casos.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Identificamos las top 8 cirugías con más fallecimientos en mujeres de 15 a 34 años
mortality_counts_mujeres_15_34 = df_mujeres_15_34[
    df_mujeres_15_34['Mortality Y / N'] == 'YES'
]['SURGERY'].value_counts()
top_8_cirugias_mort = mortality_counts_mujeres_15_34.head(8).index.tolist()

orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']

# 1. Calculamos la tasa de mortalidad (porcentaje) para estas top 8 cirugías, por casta
mort_rates_por_cirugia_caste_pct = {}
# 2. Calculamos el número de fallecimientos (n) para estas top 8 cirugías, por casta
mort_counts_por_cirugia_caste_n = {}
# 3. Calculamos el número total de cirugías (N) para estas top 8 cirugías, por casta
total_surgeries_por_cirugia_caste_N = {}

for casta in orden_castas:
    subset_caste = df_mujeres_15_34[df_mujeres_15_34['CASTE_NAME'] == casta]

    # Total de pacientes (mujeres 15-34) por cirugía en esta casta
    total_patients_per_surgery = subset_caste['SURGERY'].value_counts()

    # Pacientes fallecidos (mujeres 15-34) por cirugía en esta casta
    deceased_patients_per_surgery = subset_caste[
        subset_caste['Mortality Y / N'] == 'YES'
    ]['SURGERY'].value_counts()

    # Calcular la tasa de mortalidad (porcentaje)
    mortality_rate_series = (deceased_patients_per_surgery / total_patients_per_surgery) * 100
    mortality_rate_series = mortality_rate_series.fillna(0)

    # Calcular el número de fallecimientos
    mortality_count_series = deceased_patients_per_surgery.fillna(0)

    # Reindexar para asegurar que todas las top 8 cirugías estén presentes
    # y llenar con 0 si una cirugía no tiene casos en esta casta/demografía
    mort_rates_por_cirugia_caste_pct[casta] = mortality_rate_series.reindex(top_8_cirugias_mort, fill_value=0)
    mort_counts_por_cirugia_caste_n[casta] = mortality_count_series.reindex(top_8_cirugias_mort, fill_value=0)
    total_surgeries_por_cirugia_caste_N[casta] = total_patients_per_surgery.reindex(top_8_cirugias_mort, fill_value=0)

df_mort_rates_cirugias_mujeres_15_34_pct = pd.DataFrame(mort_rates_por_cirugia_caste_pct)
df_mort_counts_cirugias_mujeres_15_34_n = pd.DataFrame(mort_counts_por_cirugia_caste_n)
df_total_surgeries_cirugias_mujeres_15_34_N = pd.DataFrame(total_surgeries_por_cirugia_caste_N)

# 4. Trazar los resultados (tres subplots por casta)
fig, axes = plt.subplots(len(orden_castas), 3, figsize=(24, 6 * len(orden_castas)), sharey=True)
axes = axes.flatten() # Aplanamos para facilitar la iteración

plt.suptitle('Gráfico 11.5: Mortalidad en Top 8 Cirugías (Mujeres 15-34 años) por Casta: % vs n vs N',
             fontsize=18, fontweight='bold', y=1.00)

def etiquetar_barras_h(ax, bars, fmt='{:.1f}%', fontsize=8, color='black', ha='left'):
    for bar in bars:
        val = bar.get_width()
        if val > 0:
            ax.text(val + 0.5,
                    bar.get_y() + bar.get_height() / 2,
                    fmt.format(val),
                    va='center', ha=ha, fontsize=fontsize, color=color)

for idx, casta in enumerate(orden_castas):
    # Obtener el número total de pacientes (mujeres 15-34) para el título
    n_casta_total = len(df_mujeres_15_34[df_mujeres_15_34['CASTE_NAME'] == casta])

    # --- Gráfico de Porcentaje de Mortalidad ---
    ax_pct = axes[idx * 3] # Primera columna para porcentajes
    mort_data_pct = df_mort_rates_cirugias_mujeres_15_34_pct[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data_pct.empty and mort_data_pct.max() > 0:
        bars_pct = ax_pct.barh(mort_data_pct.index, mort_data_pct.values, color='darkred', edgecolor='white')
        etiquetar_barras_h(ax_pct, bars_pct, fmt='{:.1f}%', ha='left')
        max_xlim_pct = mort_data_pct.max() * 1.3
    else:
        ax_pct.text(0.5, 0.5, 'Sin datos de mortalidad (%)', horizontalalignment='center', verticalalignment='center', transform=ax_pct.transAxes, fontsize=10, color='gray')
        max_xlim_pct = 1

    ax_pct.set_title(f'{casta} - % Mortalidad (total = {n_casta_total:,})', fontsize=11, fontweight='bold')
    ax_pct.set_xlabel('% Mortalidad')
    ax_pct.set_xlim(0, max_xlim_pct)
    ax_pct.tick_params(axis='y', labelsize=9)

    # --- Gráfico de Número Absoluto de Fallecimientos (n) ---
    ax_n = axes[idx * 3 + 1] # Segunda columna para el número (n)
    mort_data_n = df_mort_counts_cirugias_mujeres_15_34_n[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data_n.empty and mort_data_n.max() > 0:
        bars_n = ax_n.barh(mort_data_n.index, mort_data_n.values, color='steelblue', edgecolor='white')
        etiquetar_barras_h(ax_n, bars_n, fmt='{:.0f}', ha='left') # Formato sin decimales para 'n'
        max_xlim_n = mort_data_n.max() * 1.3
    else:
        ax_n.text(0.5, 0.5, 'Sin fallecimientos (n)', horizontalalignment='center', verticalalignment='center', transform=ax_n.transAxes, fontsize=10, color='gray')
        max_xlim_n = 1

    ax_n.set_title(f'{casta} - N° Fallecimientos (n)', fontsize=11, fontweight='bold')
    ax_n.set_xlabel('N° de fallecimientos')
    ax_n.set_xlim(0, max_xlim_n)
    ax_n.tick_params(axis='y', labelsize=9)

    # --- Gráfico de Número Total de Cirugías (N) ---
    ax_N = axes[idx * 3 + 2] # Tercera columna para el número (N) de cirugías realizadas
    total_surgeries_data_N = df_total_surgeries_cirugias_mujeres_15_34_N[casta].sort_values(ascending=True) # Ascendente para barh

    if not total_surgeries_data_N.empty and total_surgeries_data_N.max() > 0:
        bars_N = ax_N.barh(total_surgeries_data_N.index, total_surgeries_data_N.values, color='mediumseagreen', edgecolor='white')
        etiquetar_barras_h(ax_N, bars_N, fmt='{:.0f}', ha='left') # Formato sin decimales para 'N'
        max_xlim_N = total_surgeries_data_N.max() * 1.3
    else:
        ax_N.text(0.5, 0.5, 'Sin cirugías realizadas (N)', horizontalalignment='center', verticalalignment='center', transform=ax_N.transAxes, fontsize=10, color='gray')
        max_xlim_N = 1

    ax_N.set_title(f'{casta} - N° Total de Cirugías (N)', fontsize=11, fontweight='bold')
    ax_N.set_xlabel('N° de cirugías')
    ax_N.set_xlim(0, max_xlim_N)
    ax_N.tick_params(axis='y', labelsize=9)

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Ajustar layout para hacer espacio para el suptitle
add_chart(plt.gcf())

"""## Gráfico 11.6: Top 8 Cirugías con Mortalidad (%, n y N) en Niñas (0-17 años) por Casta"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Reutilizamos df_ninas_0_17 del análisis anterior, que ya está filtrado para Female (Child) de 0 a 17 años.

# 1. Identificamos las top 8 SURGERY con más fallecimientos en este grupo
mortality_counts_ninas_0_17_surgery = df_ninas_0_17[
    df_ninas_0_17['Mortality Y / N'] == 'YES'
]['SURGERY'].value_counts()

top_8_cirugias_ninas_mort = mortality_counts_ninas_0_17_surgery.head(8).index.tolist()

# Asegurarse de que haya al menos una cirugía si el DataFrame no está vacío
if not top_8_cirugias_ninas_mort and not df_ninas_0_17.empty:
    print("Advertencia: No se encontraron fallecimientos en niñas de 0-17 años para determinar las top 8 cirugías.")

# 2. Calculamos la tasa de mortalidad (porcentaje) para estas top 8 cirugías, por casta
mort_rates_por_cirugia_caste_pct_ninas = {}
# 3. Calculamos el número de fallecimientos (n) para estas top 8 cirugías, por casta
mort_counts_por_cirugia_caste_n_ninas = {}
# 4. Calculamos el número total de cirugías (N) para estas top 8 cirugías, por casta
total_surgeries_por_cirugia_caste_N_ninas = {}

orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']

for casta in orden_castas:
    subset_caste = df_ninas_0_17[df_ninas_0_17['CASTE_NAME'] == casta]

    # Total de pacientes (niñas 0-17) por cirugía en esta casta
    total_patients_per_surgery = subset_caste['SURGERY'].value_counts()

    # Pacientes fallecidos (niñas 0-17) por cirugía en esta casta
    deceased_patients_per_surgery = subset_caste[
        subset_caste['Mortality Y / N'] == 'YES'
    ]['SURGERY'].value_counts()

    # Calcular la tasa de mortalidad (porcentaje)
    mortality_rate_series = (deceased_patients_per_surgery / total_patients_per_surgery) * 100
    mortality_rate_series = mortality_rate_series.fillna(0)

    # Calcular el número de fallecimientos
    mortality_count_series = deceased_patients_per_surgery.fillna(0)

    # Calcular el número total de cirugías
    total_surgeries_series = total_patients_per_surgery.fillna(0)

    # Reindexar para asegurar que todas las top 8 cirugías estén presentes
    # y llenar con 0 si una cirugía no tiene casos en esta casta/demografía
    mort_rates_por_cirugia_caste_pct_ninas[casta] = mortality_rate_series.reindex(top_8_cirugias_ninas_mort, fill_value=0)
    mort_counts_por_cirugia_caste_n_ninas[casta] = mortality_count_series.reindex(top_8_cirugias_ninas_mort, fill_value=0)
    total_surgeries_por_cirugia_caste_N_ninas[casta] = total_surgeries_series.reindex(top_8_cirugias_ninas_mort, fill_value=0)

df_mort_rates_cirugias_ninas_0_17_pct = pd.DataFrame(mort_rates_por_cirugia_caste_pct_ninas)
df_mort_counts_cirugias_ninas_0_17_n = pd.DataFrame(mort_counts_por_cirugia_caste_n_ninas)
df_total_surgeries_cirugias_ninas_0_17_N = pd.DataFrame(total_surgeries_por_cirugia_caste_N_ninas)

# 5. Trazar los resultados (tres subplots por casta)
fig, axes = plt.subplots(len(orden_castas), 3, figsize=(24, 6 * len(orden_castas)), sharey=True)
axes = axes.flatten() # Aplanamos para facilitar la iteración

plt.suptitle('Gráfico 11.6: Mortalidad en Top 8 Cirugías (Niñas 0-17 años) por Casta: % vs n vs N',
             fontsize=18, fontweight='bold', y=1.00)

def etiquetar_barras_h(ax, bars, fmt='{:.1f}%', fontsize=8, color='black', ha='left'):
    for bar in bars:
        val = bar.get_width()
        if val > 0:
            ax.text(val + 0.5,
                    bar.get_y() + bar.get_height() / 2,
                    fmt.format(val),
                    va='center', ha=ha, fontsize=fontsize, color=color)

for idx, casta in enumerate(orden_castas):
    # Obtener el número total de pacientes (niñas 0-17) para el título
    n_casta_total = len(df_ninas_0_17[df_ninas_0_17['CASTE_NAME'] == casta])

    # --- Gráfico de Porcentaje de Mortalidad ---
    ax_pct = axes[idx * 3] # Primera columna para porcentajes
    mort_data_pct = df_mort_rates_cirugias_ninas_0_17_pct[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data_pct.empty and mort_data_pct.max() > 0:
        bars_pct = ax_pct.barh(mort_data_pct.index, mort_data_pct.values, color='darkred', edgecolor='white')
        etiquetar_barras_h(ax_pct, bars_pct, fmt='{:.1f}%', ha='left')
        max_xlim_pct = mort_data_pct.max() * 1.3
    else:
        ax_pct.text(0.5, 0.5, 'Sin datos de mortalidad (%)', horizontalalignment='center', verticalalignment='center', transform=ax_pct.transAxes, fontsize=10, color='gray')
        max_xlim_pct = 1

    ax_pct.set_title(f'{casta} - % Mortalidad (total = {n_casta_total:,})', fontsize=11, fontweight='bold')
    ax_pct.set_xlabel('% Mortalidad')
    ax_pct.set_xlim(0, max_xlim_pct)
    ax_pct.tick_params(axis='y', labelsize=9)

    # --- Gráfico de Número Absoluto de Fallecimientos (n) ---
    ax_n = axes[idx * 3 + 1] # Segunda columna para el número (n)
    mort_data_n = df_mort_counts_cirugias_ninas_0_17_n[casta].sort_values(ascending=True) # Ascendente para barh

    if not mort_data_n.empty and mort_data_n.max() > 0:
        bars_n = ax_n.barh(mort_data_n.index, mort_data_n.values, color='steelblue', edgecolor='white')
        etiquetar_barras_h(ax_n, bars_n, fmt='{:.0f}', ha='left') # Formato sin decimales para 'n'
        max_xlim_n = mort_data_n.max() * 1.3
    else:
        ax_n.text(0.5, 0.5, 'Sin fallecimientos (n)', horizontalalignment='center', verticalalignment='center', transform=ax_n.transAxes, fontsize=10, color='gray')
        max_xlim_n = 1

    ax_n.set_title(f'{casta} - N° Fallecimientos (n)', fontsize=11, fontweight='bold')
    ax_n.set_xlabel('N° de fallecimientos')
    ax_n.set_xlim(0, max_xlim_n)
    ax_n.tick_params(axis='y', labelsize=9)

    # --- Gráfico de Número Total de Cirugías (N) ---
    ax_N = axes[idx * 3 + 2] # Tercera columna para el número (N) de cirugías realizadas
    total_surgeries_data_N = df_total_surgeries_cirugias_ninas_0_17_N[casta].sort_values(ascending=True) # Ascendente para barh

    if not total_surgeries_data_N.empty and total_surgeries_data_N.max() > 0:
        bars_N = ax_N.barh(total_surgeries_data_N.index, total_surgeries_data_N.values, color='mediumseagreen', edgecolor='white')
        etiquetar_barras_h(ax_N, bars_N, fmt='{:.0f}', ha='left') # Formato sin decimales para 'N'
        max_xlim_N = total_surgeries_data_N.max() * 1.3
    else:
        ax_N.text(0.5, 0.5, 'Sin cirugías realizadas (N)', horizontalalignment='center', verticalalignment='center', transform=ax_N.transAxes, fontsize=10, color='gray')
        max_xlim_N = 1

    ax_N.set_title(f'{casta} - N° Total de Cirugías (N)', fontsize=11, fontweight='bold')
    ax_N.set_xlabel('N° de cirugías')
    ax_N.set_xlim(0, max_xlim_N)
    ax_N.tick_params(axis='y', labelsize=9)

plt.tight_layout(rect=[0, 0, 1, 0.98]) # Ajustar layout para hacer espacio para el suptitle
add_chart(plt.gcf())

"""## Tabla 11.6: Mortalidad en Top 8 Cirugías (Niñas 0-17 años) por Casta: % vs n vs N"""

import pandas as pd
# from IPython.display import display, Markdown

# Asegurémonos de que top_8_cirugias_ninas_mort esté definido
# Si no lo está por alguna razón (por ejemplo, si este celda se ejecuta sola),
# lo recreamos usando el DataFrame df_ninas_0_17
if 'top_8_cirugias_ninas_mort' not in locals() or not top_8_cirugias_ninas_mort:
    mortality_counts_ninas_0_17_surgery = df_ninas_0_17[
        df_ninas_0_17['Mortality Y / N'] == 'YES'
    ]['SURGERY'].value_counts()
    top_8_cirugias_ninas_mort = mortality_counts_ninas_0_17_surgery.head(8).index.tolist()

orden_castas = ['BC', 'OC', 'SC', 'Minorities', 'ST', 'Others']

# Unir los DataFrames de porcentajes, n y N para construir la tabla completa primero
tabla_final_data = []

for surgery in top_8_cirugias_ninas_mort:
    row_data = {'Surgery': surgery}
    for casta in orden_castas:
        # Porcentaje de mortalidad
        pct = df_mort_rates_cirugias_ninas_0_17_pct.loc[surgery, casta]
        row_data[f'{casta}_%'] = f'{pct:.1f}%'

        # Número de fallecimientos (n)
        n_val = df_mort_counts_cirugias_ninas_0_17_n.loc[surgery, casta]
        row_data[f'{casta}_n'] = int(n_val) # Convertir a entero

        # Número total de cirugías (N)
        N_val = df_total_surgeries_cirugias_ninas_0_17_N.loc[surgery, casta]
        row_data[f'{casta}_N'] = int(N_val) # Convertir a entero
    tabla_final_data.append(row_data)

tabla_mortalidad_cirugias_ninas_full = pd.DataFrame(tabla_final_data)

# Reordenar las columnas para agrupar por casta (PCT, n, N para cada casta)
col_order = ['Surgery']
for casta in orden_castas:
    col_order.extend([f'{casta}_%', f'{casta}_n', f'{casta}_N'])

tabla_mortalidad_cirugias_ninas_full = tabla_mortalidad_cirugias_ninas_full[col_order]

# Ahora, generamos una tabla separada para cada casta
for casta in orden_castas:
    print(f"### Tabla 11.6: Mortalidad en Top 8 Cirugías (Niñas 0-17 años) - Casta: {casta}")

    # Seleccionar las columnas relevantes para la casta actual
    cols_for_casta = ['Surgery', f'{casta}_%', f'{casta}_n', f'{casta}_N']
    df_casta = tabla_mortalidad_cirugias_ninas_full[cols_for_casta].copy()

    # Renombrar las columnas para mayor claridad en cada tabla individual
    df_casta.columns = ['Surgery', 'Mortalidad (%)', 'n (Fallecimientos)', 'N (Total Cirugías)']

    print(df_casta)
    print("\n") # Añadir un espacio entre tablas para mejor legibilidad

# Grafico 12: Enfermedades según Casta, Sexo y Edad
# Filtramos solo Male / Female adultos
df_filtrado = df[df["SEX_clean"].isin(["Male", "Female"])].copy()

# Paso 2: nos quedamos con las 8 especialidades más frecuentes
top8 = df_filtrado["CATEGORY_NAME"].value_counts().head(8).index.tolist()
df_top = df_filtrado[df_filtrado["CATEGORY_NAME"].isin(top8)].copy()

orden_castas = ["BC", "OC", "SC", "Minorities", "ST", "Others"]
orden_edad   = ["0–17", "18–34", "35–49", "50–64", "65+"]

# GRÁFICO 12.1: Especialidades por Casta y Sexo

def etiquetar_barras_h(ax, bars, fontsize=7, umbral=2):
    for bar in bars:
        val = bar.get_width()
        if val >= umbral:
            ax.text(
                val + 0.4,                          # un poco a la derecha del borde
                bar.get_y() + bar.get_height() / 2, # centrado verticalmente
                f"{val:.1f}%",
                va="center", ha="left",
                fontsize=fontsize
            )

fig, axes = plt.subplots(3, 2, figsize=(18, 18))
axes = axes.flatten()

for idx, casta in enumerate(orden_castas):
    ax = axes[idx]
    subset = df_top[df_top["CASTE_NAME"] == casta]
    n = len(df_filtrado[df_filtrado["CASTE_NAME"] == casta])

    tabla = (subset.groupby(["CATEGORY_NAME", "SEX_clean"])
                   .size()
                   .unstack(fill_value=0))
    tabla_pct = tabla.div(tabla.sum(axis=0), axis=1) * 100
    tabla_pct = tabla_pct.sort_values("Male", ascending=True)

    y = range(len(tabla_pct))
    alto = 0.35

    bars_m = ax.barh([yi + alto for yi in y], tabla_pct["Male"],
                     height=alto, label="Male", color="steelblue", edgecolor="white")
    bars_f = ax.barh([yi for yi in y], tabla_pct["Female"],
                     height=alto, label="Female", color="salmon", edgecolor="white")

    # Etiquetas al final de cada barra
    etiquetar_barras_h(ax, bars_m, fontsize=7)
    etiquetar_barras_h(ax, bars_f, fontsize=7)

    ax.set_yticks([yi + alto / 2 for yi in y])
    ax.set_yticklabels(tabla_pct.index, fontsize=8)
    ax.set_title(f"{casta}  (n = {n:,})", fontsize=11, fontweight="bold")
    ax.set_xlabel("% dentro de cada sexo")

    # Extendemos el eje X para que entren las etiquetas
    ax.set_xlim(0, tabla_pct.max().max() * 1.25)
    ax.legend(title="Sexo", fontsize=8)

plt.suptitle("Especialidades Médicas por Casta y Sexo (Top 8)",
             fontsize=14, fontweight="bold", y=1.01)
plt.tight_layout()
add_chart(plt.gcf())

"""Nefrología domina en todas las castas sin excepción, tanto en hombres como en mujeres. Eso habla de una alta prevalencia de enfermedad renal crónica en toda la población del programa.

En ST, Poly Trauma tiene una presencia mucho mayor que en otras castas, quizas hay trabajos de mayor riesgo físico (agricultura, minería, trabajo rural).

General Surgery aparece notoriamente más en mujeres que en hombres en SC y OC — puede relacionarse con procedimientos ginecológicos clasificados bajo cirugía general.

En Minorities, Cardiology aparece más prominente que en otras castas.
"""

# Gráfico 12.2: Especialidad más común por grupo de edad y sexo
# Para cada grupo de edad, cómo se distribuyen las especialidades entre hombres y mujeres

def etiquetar_barras_h(ax, bars, fontsize=7, umbral=2):
    for bar in bars:
        val = bar.get_width()
        if val >= umbral:
            ax.text(
                val + 0.4,                          # un poco a la derecha del borde
                bar.get_y() + bar.get_height() / 2, # centrado verticalmente
                f"{val:.1f}%",
                va="center", ha="left",
                fontsize=fontsize
            )
fig, axes = plt.subplots(3, 2, figsize=(18, 16))
axes = axes.flatten()

for idx, edad in enumerate(orden_edad):
    ax = axes[idx]
    subset = df_top[df_top["GRUPO_EDAD"] == edad]
    n = len(subset)

    tabla = (subset.groupby(["CATEGORY_NAME", "SEX_clean"])
                   .size()
                   .unstack(fill_value=0))
    tabla_pct = tabla.div(tabla.sum(axis=0), axis=1) * 100
    tabla_pct = tabla_pct.sort_values("Male", ascending=True)

    y = range(len(tabla_pct))
    alto = 0.35

    bars_m = ax.barh([yi + alto for yi in y], tabla_pct["Male"],
                     height=alto, label="Male", color="steelblue", edgecolor="white")
    bars_f = ax.barh([yi for yi in y], tabla_pct["Female"],
                     height=alto, label="Female", color="salmon", edgecolor="white")

    etiquetar_barras_h(ax, bars_m, fontsize=7)
    etiquetar_barras_h(ax, bars_f, fontsize=7)

    ax.set_yticks([yi + alto / 2 for yi in y])
    ax.set_yticklabels(tabla_pct.index, fontsize=8)
    ax.set_title(f"Grupo {edad}  (n = {n:,})", fontsize=11, fontweight="bold")
    ax.set_xlabel("% dentro de cada sexo")
    ax.set_xlim(0, tabla_pct.max().max() * 1.25)
    ax.legend(title="Sexo", fontsize=8)

axes[5].set_visible(False)

plt.suptitle("Especialidades Médicas por Grupo de Edad y Sexo",
             fontsize=14, fontweight="bold", y=1.01)
plt.tight_layout()
add_chart(plt.gcf())

"""Grupo 0–17 (n=485):General Surgery domina, especialmente en niñas,  puede incluir procedimientos abdominales de urgencia (apendicitis, hernias).
Poly Trauma es mayoria masculino en este grupo.
Nefrología ya aparece incluso en menores, lo que sugiere enfermedad renal crónica congénita o temprana.

Grupo 18–34 (n=6.703): Nefrología ya salta al primer lugar.
General Surgery es l alta en mujeres, probablemente entran procedimientos ginecológicos clasificados como cirugía general.

Grupo 35–49 (n=12.269): Nefrología ocupa 30% para ambos sexos de forma muy pareja, la brecha de género desaparece.

Grupo 50–64 (n=13.720): Nefrología domina fuerte.

Grupo 65+: Nefrología sigue siendo la especialidad dominante, pero Neurología aparece mucho más en mujeres. Poly Trauma en el grupo 65+ es llamativo — caídas en adultos mayores son una causa frecuente.
"""

# Exportacion a JSON
DATASET_ID = 2
DATASET_TITLE = 'NTR Arogya Seva'
ARTIFACT_FILENAME = f'artifact_{DATASET_ID}.json'

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, '..', 'public', 'datasets')

artifact = {
    'dataset_id': DATASET_ID,
    'title': DATASET_TITLE,
    'generated_at': datetime.now(timezone.utc).isoformat(),
    'notes': "Análisis de pacientes que recibieron cirugías/procedimientos médicos cubiertos por el seguro público de India.",
    'charts': charts,
}

os.makedirs(OUTPUT_DIR, exist_ok=True)
output_path = os.path.join(OUTPUT_DIR, ARTIFACT_FILENAME)
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(json.dumps(artifact, ensure_ascii=False))
print(f'\nPipeline completado exitosamente.')
print(f'   Archivo guardado en: {output_path}')
