# -*- coding: utf-8 -*-
"""TP Final Taller II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1ESWDNcLKQtPcKMybujkFPRr4aDo-ry

# Dataset

Analizamos la población general del dataset para
comprender la estructura demográfica del conjunto de casi 480.000 registros
de pacientes cubiertos por el programa de salud pública.

El trabajo muestra quién accede a un sistema de salud pública en India, cómo son esas personas y si la casta social de origen genera diferencias reales en los resultados de salud.
"""

# Importamos las librerías

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import io

# Configuración visual general
sns.set_theme(style="whitegrid")  # Estilo de fondo para los gráficos
plt.rcParams["figure.figsize"] = (8, 5)  # Tamaño por defecto de los gráficos

#Carga del dataset
df = pd.read_csv("/content/ntrarogyaseva.csv")

#Limpieza del dataset
# Define los nombres de las columnas según la estructura original, incluyendo un 'ID' para la primera columna
nombres_columnas = [
    'ID', 'AGE', 'SEX', 'CASTE_NAME', 'CATEGORY_CODE', 'CATEGORY_NAME',
    'SURGERY_CODE', 'SURGERY', 'VILLAGE', 'MANDAL_NAME', 'DISTRICT_NAME',
    'PREAUTH_DATE', 'PREAUTH_AMT', 'CLAIM_DATE', 'CLAIM_AMOUNT', 'HOSP_NAME',
    'HOSP_TYPE', 'HOSP_LOCATION', 'HOSP_DISTRICT', 'SURGERY_DATE',
    'DISCHARGE_DATE', 'Mortality Y / N', 'MORTALITY_DATE', 'SRC_REGISTRATION'
]

# Lee el archivo en memoria y elimina las comillas dobles al principio y al final de cada línea
lineas_limpias = []
with open('/content/ntrarogyaseva.csv', 'r', encoding='utf-8') as f:
    for linea in f:
        linea = linea.strip() # Elimina espacios en blanco iniciales/finales y saltos de línea
        if linea.startswith('"') and linea.endswith('"'):
            linea = linea[1:-1] # Elimina la comilla del principio y del final
        lineas_limpias.append(linea)

# Convierte la lista de líneas limpias en un objeto que Pandas pueda leer como un archivo
archivo_limpio = io.StringIO('\n'.join(lineas_limpias))

# Carga el DataFrame usando el archivo preprocesado, especificando los nombres de las columnas y sin encabezado.
# Se quita `index_col=0` para tratar a 'ID' como una columna común en lugar del índice del DataFrame.
# Se usa `on_bad_lines='skip'` para omitir filas mal formateadas, y `dtype=str` para evitar advertencias de tipos mixtos.
df = pd.read_csv(archivo_limpio, header=None, names=nombres_columnas, on_bad_lines='skip', dtype=str)

# La primera fila sigue siendo el encabezado del CSV original, por lo que la eliminamos.
df = df.iloc[1:].copy()

# Limpieza de Mortality Y / N
df["Mortality Y / N"] = df["Mortality Y / N"].replace('17/09/2017 00:00:00', np.nan)
df = df.dropna(subset=['Mortality Y / N'])

# Conversión de tipos
df["AGE"] = pd.to_numeric(df["AGE"], errors='coerce')
df["CLAIM_AMOUNT"] = pd.to_numeric(df["CLAIM_AMOUNT"], errors='coerce')
df["PREAUTH_AMT"] = pd.to_numeric(df["PREAUTH_AMT"], errors='coerce')

# Muestra las primeras filas para verificar el resultado
df.head(3)

# Limpiez de la variable SEX

print("Antes de limpiar")
print(df["SEX"].value_counts())
print()

df["SEX_clean"] = df["SEX"].str.strip().str.lower()
mapeo_sexo = {
    "male":           "Male",
    "female":         "Female",
    "male(child)":    "Male (Child)",
    "female(child)":  "Female (Child)"
}
df["SEX_clean"] = df["SEX_clean"].map(mapeo_sexo)
df["ES_MENOR"] = df["SEX_clean"].str.contains("Child").map({True: "Menor", False: "Adulto"})

print("Después de limpiar")
print(df["SEX_clean"].value_counts())
print()
print("Nulos en SEX_clean:", df["SEX_clean"].isnull().sum())
print()
print("Columna ES_MENOR:")
print(df["ES_MENOR"].value_counts())

# Gráfico 1: Distribución de edades
plt.figure(figsize=(8, 5))
sns.histplot(df["AGE"].dropna(), bins=30, kde=True, color="steelblue")

media = df["AGE"].mean()
mediana = df["AGE"].median()
plt.axvline(media, color="red", linestyle="--", linewidth=1.5, label=f"Promedio: {media:.1f} años")
plt.axvline(mediana, color="orange", linestyle="--", linewidth=1.5, label=f"Mediana: {mediana:.0f} años")

plt.title("Gráfico 1: Distribución de Edades de los Pacientes")
plt.xlabel("Edad")
plt.ylabel("Cantidad de pacientes")
plt.legend()
plt.tight_layout()
plt.show()

"""Distribución de edades de los ~480k pacientes con líneas de media (44,9) y mediana (47).

El programa atiende principalmente a adultos entre 35 y 65 años. La mediana es 47 años, y hay un pequeño pico en la infancia que vamos a retomar más adelante cuando hablemos de acceso por género.
"""

#Gráfico 2: Distribución de Edad por Grupos
bins   = [0, 17, 34, 49, 64, 110]
labels = ["0–17", "18–34", "35–49", "50–64", "65+"]
df["GRUPO_EDAD"] = pd.cut(df["AGE"], bins=bins, labels=labels, right=True)

orden_castas = ["BC", "OC", "SC", "Minorities", "ST", "Others"]
orden_edad   = ["0–17", "18–34", "35–49", "50–64", "65+"]

plt.figure(figsize=(8, 5))
orden_edad_count = df["GRUPO_EDAD"].value_counts().reindex(orden_edad)
bars = plt.bar(orden_edad_count.index, orden_edad_count.values,
               color="steelblue", edgecolor="white")

total_edad = orden_edad_count.sum()
for bar, val in zip(bars, orden_edad_count.values):
    plt.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 1500,
             f"{val:,}\n({val/total_edad*100:.1f}%)",
             ha="center", va="bottom", fontsize=9)

plt.title("Gráfico 2: Distribución de Pacientes por Grupo de Edad")
plt.xlabel("Grupo de edad")
plt.ylabel("Cantidad de pacientes")
plt.ylim(0, orden_edad_count.max() * 1.2)
plt.tight_layout()
plt.show()

"""Agrupación en cinco franjas etarias (0–17, 18–34, 35–49, 50–64, 65+) con n y % de cada una.

Al agrupar en franjas, vemos que el 61% de los pacientes tiene entre 35 y 64 años. Esta agrupación la vamos a usar como variable de control en todos los análisis de mortalidad, porque la edad es el factor individual que más influye en el riesgo de fallecer.
"""

# Gráfico 3: Distribución por Sexo
fig, ax = plt.subplots(figsize=(8, 5))

valores = df["SEX_clean"].value_counts()
colores = ["steelblue", "salmon", "skyblue", "lightcoral"]
bars = ax.bar(valores.index, valores.values, color=colores, edgecolor="white")

total = valores.sum()
for bar, val in zip(bars, valores.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 1500,
            f"{val:,}\n({val/total*100:.1f}%)",
            ha="center", va="bottom", fontsize=9)

ax.set_title("Gráfico 3: Distribución de Pacientes por Sexo")
ax.set_xlabel("Sexo")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores.max() * 1.18)
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""Proporción de Male, Female, Male (Child), Female (Child) en el total.

Acá aparece el primer dato fuerte: hay 54,4% hombres adultos y 37,3% mujeres adultas. En la infancia también hay brecha: 5,2% son niños y 3,1% niñas. Esto puede deberse en parte a que ciertas enfermedades del programa son más comunes en varones, pero también puede haber barreras de acceso para mujeres y niñas.
"""

# Gráfico 4: Razón de género por grupo etario
sex_grupo = df.groupby(["GRUPO_EDAD", "SEX_clean"]).size().unstack(fill_value=0)

ratio_genero = pd.Series({
    "0–17":  sex_grupo.loc["0–17", "Female (Child)"] / sex_grupo.loc["0–17", "Male (Child)"],
    "18–34": sex_grupo.loc["18–34", "Female"] / sex_grupo.loc["18–34", "Male"],
    "35–49": sex_grupo.loc["35–49", "Female"] / sex_grupo.loc["35–49", "Male"],
    "50–64": sex_grupo.loc["50–64", "Female"] / sex_grupo.loc["50–64", "Male"],
    "65+":   sex_grupo.loc["65+", "Female"] / sex_grupo.loc["65+", "Male"],
})

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(ratio_genero.index, ratio_genero.values, color="#8856a7", edgecolor="white")
ax.axhline(1.0, color="gray", linestyle="--", linewidth=1.2, label="Paridad (1 mujer : 1 hombre)")

for bar, val in zip(bars, ratio_genero.values):
    ax.text(bar.get_x() + bar.get_width()/2, val + 0.02, f"{val:.2f}",
            ha="center", fontsize=9)

ax.set_ylabel("Pacientes mujeres por cada paciente varón")
ax.set_title("Gráfico 4:Razón de género por grupo etario - población general")
ax.set_ylim(0, 1.1)
ax.legend()
plt.tight_layout()
plt.show()

"""Mujeres por cada hombre en cada franja etaria de la población total.

La brecha de género no es pareja en todas las edades: en adultos jóvenes hay solo 0,47 mujeres por cada hombre, probablemente por el efecto del politrauma. Pero lo más llamativo es la niñez: 0,54 niñas por cada niño.
"""

# Gráfico 5: Especialidad por Grupo de edad
top10_cat = df["CATEGORY_NAME"].value_counts().head(10).index
sub = df[df["CATEGORY_NAME"].isin(top10_cat)]
tabla = pd.crosstab(sub["CATEGORY_NAME"], sub["GRUPO_EDAD"], normalize="index") * 100

fig, ax = plt.subplots(figsize=(10, 6))
sns.heatmap(tabla.reindex(columns=orden_edad), annot=True, fmt=".0f",
            cmap="YlOrRd", cbar_kws={"label": "% dentro de la especialidad"}, ax=ax)
ax.set_title("Gráfico 5: Distribución etaria dentro de cada especialidad médica")
ax.set_xlabel("Grupo de edad")
ax.set_ylabel("Especialidad")
plt.tight_layout()
plt.show()

"""Para cada una de las 10 especialidades más frecuentes, qué porcentaje de sus pacientes cae en cada franja etaria.

Este mapa de calor muestra que cada especialidad tiene un perfil de edad muy diferente. Pediatría es 100% niños, ortopedia se concentra en adultos jóvenes por fracturas deportivas y laborales, y cardiología en mayores de 50. No se puede comparar mortalidad entre especialidades sin controlar por edad.
"""

# Gráfico 6: Categorías médicas más frecuentes
plt.figure(figsize=(10, 5))
df["CATEGORY_NAME"].value_counts().head(10).plot(kind="barh", color="teal")
plt.title("Gráfico 6: Categorías Médicas más Frecuentes")
plt.xlabel("Casos")
plt.ylabel("Categoría médica")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

"""Top 10 especialidades por volumen de casos.

Nefrología es la especialidad más usada del programa por lejos. En India, la insuficiencia renal crónica vinculada a diabetes e hipertensión mal controladas genera una demanda enorme de hemodiálisis. Oncología y politrauma completan el podio. Este perfil epidemiológico podría ser clave cuando analicemos mortalidad por especialidad.
"""

# Gráfico 7: Tipo de Hospital
fig, ax = plt.subplots(figsize=(6, 5))

valores_hosp = df["HOSP_TYPE"].value_counts()
etiquetas = {"C": "Corporativo\n(Privado)", "G": "Gobierno\n(Público)"}
bars = ax.bar(
    [etiquetas.get(x, x) for x in valores_hosp.index],
    valores_hosp.values,
    color=["salmon", "steelblue"],
    edgecolor="white", width=0.5
)

total_hosp = valores_hosp.sum()
for bar, val in zip(bars, valores_hosp.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 2000,
            f"{val:,}\n({val/total_hosp*100:.1f}%)",
            ha="center", va="bottom", fontsize=10)

ax.set_title("Gráfico 7: Procedimientos por Tipo de Hospital")
ax.set_ylabel("Cantidad de casos")
ax.set_ylim(0, valores_hosp.max() * 1.18)
plt.tight_layout()

"""77,0% privado vs 23,0% público.

El 77% de los procedimientos se hace en hospitales privados, aunque el programa está financiado por el Estado. Este dato es importante porque más adelante vamos a ver que la mortalidad en el sector público casi duplica a la del privado, así que a qué tipo de hospital accede cada casta importa mucho
"""

# Gráfico 8: Mortalidad General
fig, ax = plt.subplots(figsize=(6, 5))

valores_mort = df["Mortality Y / N"].value_counts()
bars = ax.bar(["No falleció", "Falleció"],
              valores_mort.values,
              color=["steelblue", "#c94444"],
              edgecolor="white", width=0.5)

total_mort = valores_mort.sum()
for bar, val in zip(bars, valores_mort.values):
    ax.text(bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 2000,
            f"{val:,}\n({val/total_mort*100:.2f}%)",
            ha="center", va="bottom", fontsize=10)

ax.set_title("Gráfico 8: Mortalidad de los Pacientes")
ax.set_ylabel("Cantidad de pacientes")
ax.set_ylim(0, valores_mort.max() * 1.18)
plt.tight_layout()
plt.show()

"""2,11% de mortalidad general sobre ~480k pacientes.

La mortalidad general del programa es del 2,11%. Este número es nuestra línea de base: cuando más adelante hablemos de que castas tiene tal o cual porcentaje, siempre va a ser en relación a este dato.
"""

# Gráfico 9: Castas
fig, ax = plt.subplots(figsize=(10, 5))

datos = df["CASTE_NAME"].value_counts()
total_casta = datos.sum()

bars = ax.barh(datos.index[::-1], datos.values[::-1],
               color="teal", edgecolor="white")

for bar, val in zip(bars, datos.values[::-1]):
    ax.text(bar.get_width() + 500,
            bar.get_y() + bar.get_height() / 2,
            f"{val:,}  ({val/total_casta*100:.1f}%)",
            va="center", fontsize=9)

ax.set_title("Gráfico 9: Distribución de Pacientes por Casta")
ax.set_xlabel("Cantidad de casos")
ax.set_ylabel("Casta")
ax.set_xlim(0, datos.max() * 1.22)
plt.tight_layout()
plt.show()

"""BC: 51,3%, OC: 23,8%, SC: 16,0%, Minorías: 6,1%, ST: 2,7% y Others: 0,1%.

BC concentra poco más de la mitad del dataset y OC casi el 24%. Entre los dos suman el 75% del total, lo que los hace estadísticamente los grupos más robustos para comparar. También noto que ST, la casta indígena más postergada, es apenas el 3% a pesar de tener necesidades de salud importantes, lo que ya sugiere una barrera de acceso.
"""

# Gráfico 10: Edad según Casta
plt.figure(figsize=(10, 5))
sns.boxplot(data=df, x="CASTE_NAME", y="AGE",
            hue="CASTE_NAME", order=orden_castas, palette="Set2", legend=False)

medias = df.groupby("CASTE_NAME")["AGE"].mean()
for i, casta in enumerate(orden_castas):
    m = medias[casta]
    plt.text(i, -8, f"x̄={m:.1f}", ha="center", fontsize=9, color="dimgray")

plt.title("Gráfico 10: Distribución de Edad según Casta")
plt.xlabel("Casta")
plt.ylabel("Edad")
plt.ylim(-12, df["AGE"].max() + 5)
plt.tight_layout()
plt.show()

print("Edad promedio por casta:")
print(df.groupby("CASTE_NAME")["AGE"].mean().round(1).sort_values(ascending=False))

"""OC es la casta más vieja (49,2 años), ST la más joven (38,9) y BC queda en 44,2.

Al mirar la edad promedio por casta, aparece un patrón muy ordenado: OC es la más vieja con 49,2 años de promedio, y ST la más joven con 38,9. BC está en 44,2. Esta diferencia de 5 años entre BC y OC es importante porque la edad por sí sola influye en el riesgo de morir. Por eso, cuando más adelante comparemos mortalidad, vamos a tener que ajustar por edad para que la comparación sea justa.
"""

# Gráfico 11: Mortalidad por Casta + tamaño de población
mortalidad_casta = (df.groupby("CASTE_NAME")["Mortality Y / N"]
                      .value_counts(normalize=True)
                      .unstack(fill_value=0) * 100)
poblacion_casta = df["CASTE_NAME"].value_counts()

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

valores_mort = mortalidad_casta["YES"].reindex(orden_castas)
bars1 = ax1.bar(orden_castas, valores_mort, color="#c94444", edgecolor="white", width=0.6)
ax1.set_title("Tasa de Mortalidad por Casta (%)", fontsize=12)
ax1.set_ylabel("% de pacientes fallecidos")
ax1.set_ylim(0, valores_mort.max() * 1.25)

for bar, val in zip(bars1, valores_mort):
    ax1.text(bar.get_x() + bar.get_width() / 2,
             val + 0.04, f"{val:.2f}%",
             ha="center", va="bottom", fontsize=10)

valores_pob = poblacion_casta.reindex(orden_castas)
total_pob = valores_pob.sum()
bars2 = ax2.bar(orden_castas, valores_pob, color="steelblue", edgecolor="white", width=0.6)
ax2.set_title("Cantidad de Pacientes por Casta (n)", fontsize=12)
ax2.set_ylabel("Cantidad de pacientes")
ax2.set_ylim(0, valores_pob.max() * 1.18)

for bar, val in zip(bars2, valores_pob):
    ax2.text(bar.get_x() + bar.get_width() / 2,
             val + 1000,
             f"{val:,}\n({val/total_pob*100:.1f}%)",
             ha="center", va="bottom", fontsize=9)

plt.suptitle("Gráfico 11: Mortalidad y Representación por Casta", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""Panel izquierdo: mortalidad por casta. Panel derecho: tamaño de cada casta.

La mortalidad sigue bastante el orden jerárquico de las castas: las más postergadas tienen algo más de mortalidad. Pero la diferencia entre BC y OC es pequeña. Y acá hay una trampa: BC es 5 años más joven que OC. Si comparamos así, tal vez la diferencia real está subestimada, porque los pacientes de BC deberían morir menos por ser más jóvenes.
"""

# Gráfico 12: Distribución de Sexo dentro de cada Casta
adultos = df[df["SEX_clean"].isin(["Male", "Female"])].copy()
casta_sexo = (adultos.groupby(["CASTE_NAME", "SEX_clean"])
                      .size()
                      .unstack(fill_value=0))
casta_sexo_pct = casta_sexo.div(casta_sexo.sum(axis=1), axis=0) * 100

print("Porcentaje de hombres y mujeres por casta:")
print(casta_sexo_pct.round(1))
print()

ax = casta_sexo_pct.reindex(orden_castas).plot(
    kind="bar",
    stacked=False,
    color=["salmon", "steelblue"],
    figsize=(10, 5),
    edgecolor="white",
    width=0.7
)

plt.title("Gráfico 12: Distribución de Sexo dentro de cada Casta (% adultos)")
plt.xlabel("Casta")
plt.ylabel("Porcentaje (%)")
plt.xticks(rotation=15)
plt.legend(title="Sexo", bbox_to_anchor=(1.01, 1), loc="upper left")

for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f}%",
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.show()

"""BC tiene 58,6% varones, OC 60,4%. Composición casi idéntica.

Este gráfico es el que valida metodológicamente la comparación BC vs OC: ambas castas tienen una composición de género prácticamente idéntica. Si encontramos diferencias de mortalidad entre ellas, no vamos a poder decir que son por el sexo.
"""

# Gráfico 13: Tipo de Hospital por Casta (BC, OC y resto)
hosp_casta = (df.groupby(["CASTE_NAME", "HOSP_TYPE"])
                .size()
                .unstack(fill_value=0))
hosp_casta_pct = hosp_casta.div(hosp_casta.sum(axis=1), axis=0) * 100

ax = hosp_casta_pct.reindex(orden_castas).rename(
    columns={"G": "Gobierno (Público)", "C": "Corporativo (Privado)"}
).plot(
    kind="bar",
    stacked=False,
    color=["steelblue", "salmon"],
    figsize=(10, 5),
    edgecolor="white",
    width=0.7
)

plt.title("Gráfico 13: Tipo de Hospital según Casta (%)")
plt.xlabel("Casta")
plt.ylabel("Porcentaje (%)")
plt.xticks(rotation=15)
plt.legend(title="Tipo de Hospital", bbox_to_anchor=(1.01, 1), loc="upper left")

for p in ax.patches:
    ax.annotate(f"{p.get_height():.1f}%",
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha="center", va="bottom", fontsize=8)

plt.tight_layout()
plt.show()

"""OC accede al privado en 82,7%, BC en 75,8%, ST en 69,1%.

OC accede al sector privado 6,9 puntos más que BC. Y como ya vimos que la mortalidad en el sector privado es mucho menor, esto empieza a sugerir que parte de cualquier diferencia de mortalidad que veamos entre castas podría estar mediada por a qué tipo de hospital accede cada una
"""

# Subconjunto de trabajo: solo BC y OC, adultos (Male/Female)
df_bc_oc = df[df["CASTE_NAME"].isin(["BC", "OC"])].copy()
df_bc_oc_adultos = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male", "Female"])].copy()

colores_casta = {"BC": "#4C72B0", "OC": "#DD8452"}

# Gráfico 14: Edad por Casta y Sexo (BC vs OC)
plt.figure(figsize=(8, 6))
sns.boxplot(data=df_bc_oc_adultos, x="CASTE_NAME", y="AGE",
            hue="SEX_clean", order=["BC", "OC"],
            palette=["salmon", "steelblue"])

plt.title("Gráfico 14: Distribución de Edad por Casta y Sexo (BC vs OC)")
plt.xlabel("Casta")
plt.ylabel("Edad")
plt.legend(title="Sexo")
plt.tight_layout()
plt.show()

print("Edad promedio - BC vs OC, por sexo:")
print(df_bc_oc_adultos.groupby(["CASTE_NAME", "SEX_clean"])["AGE"].mean().round(1))

"""La brecha de edad entre BC y OC persiste tanto en varones como en mujeres.

Al desagregar por sexo, confirmamos que la diferencia de edad entre BC y OC es real y se mantiene en ambos géneros: OC es siempre unos años mayor. No es un artefacto estadístico.
"""

# Gráfico 15: Brecha de género en el acceso, niñez vs adultez, BC vs OC
colores_casta = {"BC": "#4C72B0", "OC": "#DD8452"}
ratios = pd.DataFrame({
    "BC": [0.601, 0.708],
    "OC": [0.568, 0.657]
}, index=["Niñas / Niños (0–17)", "Mujeres / Hombres (18+)"])

fig, ax = plt.subplots(figsize=(8, 5))
ratios.plot(kind="bar", ax=ax, color=[colores_casta["BC"], colores_casta["OC"]],
            edgecolor="white", width=0.7)
ax.axhline(1.0, color="gray", linestyle="--", linewidth=1, label="Paridad (1:1)")
ax.set_ylabel("Pacientes mujeres por cada paciente varón")
ax.set_title("Gráfico 15: Brecha de género en el acceso al sistema: niñez vs adultez (BC vs OC)")
ax.set_xticklabels(ratios.index, rotation=10)
ax.legend(title="Casta")

# Etiquetas con el valor arriba de cada barra
for contenedor in ax.containers:
    if hasattr(contenedor, "patches"):  # evita la línea de paridad
        ax.bar_label(contenedor, fmt="%.2f", padding=3, fontsize=9)

ax.set_ylim(0, 1.05)
plt.tight_layout()
plt.show()

"""Niñas/niños: BC 0,60 / OC 0,57. Mujeres/hombres adultos: BC 0,71 / OC 0,66.

Acá está uno de los hallazgos más importantes del trabajo. La brecha de género en el acceso al sistema es sistemáticamente mayor en la niñez que en la adultez, en las dos castas. En BC, 0,60 niñas por cada niño, pero 0,71 mujeres por cada hombre adulto. Y lo más llamativo: la brecha es un poco peor en OC, la casta más privilegiada. Eso nos dice que este problema no es de casta, es un patrón social más amplio.
"""

# Gráfico 16: Edad promedio al ingreso, niñas vs niños (BC vs OC)
# Define df_bc_oc para asegurar que esté disponible en esta celda
df_bc_oc = df[df["CASTE_NAME"].isin(["BC", "OC"])].copy()

ninos_bc_oc = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male (Child)", "Female (Child)"])]

edad_prom = ninos_bc_oc.groupby(["CASTE_NAME", "SEX_clean"])["AGE"].mean().unstack()

fig, ax = plt.subplots(figsize=(8, 5))
x = range(len(["BC", "OC"]))
ancho = 0.35
for i, sexo in enumerate(["Male (Child)", "Female (Child)"]):
    valores = edad_prom[sexo].reindex(["BC", "OC"])
    bars = ax.bar([xi + i*ancho for xi in x], valores, width=ancho,
                  label=sexo, color=["steelblue", "salmon"][i], edgecolor="white")
    for bar, val in zip(bars, valores):
        ax.text(bar.get_x()+bar.get_width()/2, val+0.05, f"{val:.2f}",
                ha="center", fontsize=9)

ax.set_xticks([xi + ancho/2 for xi in x])
ax.set_xticklabels(["BC", "OC"])
ax.set_ylabel("Edad promedio (años)")
ax.set_title("Gráfico 16: Edad promedio al ingreso al sistema - niñas vs niños (BC vs OC)")
ax.legend(title="Sexo")
plt.tight_layout()
plt.show()

"""Las niñas llegan más pequeñas que los niños: BC 3,62 vs 4,15; OC 3,80 vs 4,95 años.

Entre los niños que sí son atendidos, las niñas llegan al sistema siendo más pequeñas que los niños: en OC, la diferencia es de casi un año entero. Eso es compatible con pensar que las familias llevan a las niñas solo cuando el cuadro es urgente y no puede esperar. A los niños los llevan también por motivos más leves, a lo largo de un rango de edad más amplio.
"""

# Gráfico 17: Mortalidad por Grupo de Edad - BC vs OC
mort_edad_casta = (df_bc_oc.groupby(["GRUPO_EDAD", "CASTE_NAME"])["Mortality Y / N"]
                           .apply(lambda x: (x == "YES").mean() * 100)
                           .unstack(fill_value=0)
                           .reindex(orden_edad))

n_edad_casta = (df_bc_oc.groupby(["GRUPO_EDAD", "CASTE_NAME"])
                        .size()
                        .unstack(fill_value=0)
                        .reindex(orden_edad))

fig, ax = plt.subplots(figsize=(11, 6))
x = range(len(orden_edad))
ancho = 0.35

for i, casta in enumerate(["BC", "OC"]):
    valores = mort_edad_casta[casta]
    bars = ax.bar([xi + i * ancho for xi in x], valores,
                   width=ancho, label=casta, color=colores_casta[casta], edgecolor="white")
    for bar, val, n_val in zip(bars, valores, n_edad_casta[casta]):
        ax.text(bar.get_x() + bar.get_width() / 2,
                val + 0.05,
                f"{val:.2f}%\n(n={n_val:,})",
                ha="center", va="bottom", fontsize=8)

ax.set_title("Gráfico 17: Tasa de Mortalidad por Grupo de Edad - BC vs OC")
ax.set_xlabel("Grupo de edad")
ax.set_ylabel("% mortalidad")
ax.set_xticks([xi + ancho / 2 for xi in x])
ax.set_xticklabels(orden_edad)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""BC tiene más mortalidad que OC en todos los grupos de edad, pero la brecha se achica en 65+.

BC tiene más mortalidad que OC en todos los grupos etarios, pero la diferencia no es uniforme. Es más grande en chicos y en adultos jóvenes, donde la mortalidad esperada es baja. En los mayores de 65, en cambio, la diferencia prácticamente desaparece: ahí el peso de la edad biológica domina sobre cualquier factor social.
"""

# Gráfico 18: Mortalidad por Grupo de Edad - BC vs OC
import scipy.stats as st

resultados = []
for g in orden_edad:
    sub = df_bc_oc[df_bc_oc["GRUPO_EDAD"] == g]
    bc = sub[sub["CASTE_NAME"]=="BC"]["Mortality Y / N"]
    oc = sub[sub["CASTE_NAME"]=="OC"]["Mortality Y / N"]
    p_bc, p_oc = (bc=="YES").mean(), (oc=="YES").mean()
    diff = (p_bc - p_oc) * 100
    se = np.sqrt(p_bc*(1-p_bc)/len(bc) + p_oc*(1-p_oc)/len(oc)) * 100
    resultados.append((g, diff, diff-1.96*se, diff+1.96*se))

res_df = pd.DataFrame(resultados, columns=["Grupo","Diferencia","IC_low","IC_high"])

fig, ax = plt.subplots(figsize=(8,5))
ax.errorbar(res_df["Diferencia"], res_df["Grupo"],
            xerr=[res_df["Diferencia"]-res_df["IC_low"], res_df["IC_high"]-res_df["Diferencia"]],
            fmt="o", color="#c94444", capsize=4)
ax.axvline(0, color="gray", linestyle="--")
ax.set_xlabel("Diferencia BC − OC en mortalidad, IC 95%")
ax.set_title("Gráfico 18: Forest plot: diferencia de mortalidad por grupo de edad - BC vs OC")
plt.tight_layout()
plt.show()

"""Intervalos de confianza del 95% de la diferencia BC−OC en mortalidad por franja etaria. Significativo de 0–17 a 50–64. No significativo en 65+.

Este gráfico traduce el anterior a términos estadísticos. Cada punto es la diferencia de mortalidad BC menos OC, y las líneas horizontales son el intervalo de confianza. Cuando ese intervalo no toca la línea del cero, la diferencia es estadísticamente significativa. Eso ocurre desde la niñez hasta los 64 años, aunque en 50–64 el margen es muy ajustado. En mayores de 65, el intervalo cruza ampliamente el cero: ahí no podemos afirmar que hay diferencia real.
"""

pop_estandar = df["GRUPO_EDAD"].value_counts(normalize=True)

def tasa_ajustada(casta):
    sub = df_bc_oc[df_bc_oc["CASTE_NAME"] == casta]
    tasas = sub.groupby("GRUPO_EDAD")["Mortality Y / N"].apply(lambda x: (x=="YES").mean())
    return (tasas * pop_estandar).sum() * 100

comparacion = pd.DataFrame({
    "Cruda": [
        (df_bc_oc[df_bc_oc.CASTE_NAME=="BC"]["Mortality Y / N"]=="YES").mean()*100,
        (df_bc_oc[df_bc_oc.CASTE_NAME=="OC"]["Mortality Y / N"]=="YES").mean()*100
    ],
    "Ajustada por edad": [tasa_ajustada("BC"), tasa_ajustada("OC")]
}, index=["BC", "OC"])

fig, ax = plt.subplots(figsize=(8, 5))
comparacion.plot(kind="bar", ax=ax, color=["#bbbbbb", "#c94444"], edgecolor="white")
ax.set_ylabel("% mortalidad")
ax.set_title("Gráfico 19: Mortalidad cruda vs. ajustada por edad - BC vs OC")
ax.set_xticklabels(comparacion.index, rotation=0)
ax.legend(loc="upper left", bbox_to_anchor=(1.02, 0.5))

# Etiquetas sobre cada barra
for container in ax.containers:
    ax.bar_label(container, fmt="%.2f%%", padding=4, fontsize=9)

ax.set_ylim(0, comparacion.values.max() * 1.18)
plt.tight_layout()
plt.show()

"""Mortalidad cruda BC 2,08% / OC 1,99%. Ajustada por edad: BC 1,99% / OC 1,80%.

Como BC es más joven que OC, comparar las mortalidades crudas no es del todo justo: los pacientes de BC deberían morir menos solo por ser más jóvenes. Para resolver eso, estandarizamos las tasas: calculamos cuánto moriría cada casta si tuviera la misma distribución de edades que la población total. El resultado es claro: al ajustar, la mortalidad de OC baja más que la de BC, y la brecha entre ambas casi se duplica. La comparación cruda estaba subestimando la verdadera desventaja de BC.
"""

# Gráfico 20: Especialidades Médicas - BC vs OC
top8_general = df_bc_oc_adultos["CATEGORY_NAME"].value_counts().head(8).index.tolist()
df_top8_bc_oc = df_bc_oc_adultos[df_bc_oc_adultos["CATEGORY_NAME"].isin(top8_general)].copy()

esp_casta = (df_top8_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"])
                          .size()
                          .unstack(fill_value=0))
esp_casta_pct = esp_casta.div(esp_casta.sum(axis=0), axis=1) * 100
esp_casta_pct = esp_casta_pct.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(11, 7))
y = range(len(esp_casta_pct))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], esp_casta_pct["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], esp_casta_pct["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars in [bars_bc, bars_oc]:
    for bar in bars:
        val = bar.get_width()
        ax.text(val + 0.4, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(esp_casta_pct.index, fontsize=9)
ax.set_title("Gráfico 20: Especialidades Médicas (Top 8) - BC vs OC")
ax.set_xlabel("% dentro de cada casta")
ax.set_xlim(0, esp_casta_pct.max().max() * 1.2)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""OC usa Nefrología proporcionalmente más que BC (23,6% vs 20,4%). El resto de especialidades es similar.

El perfil de especialidades es bastante similar entre BC y OC, con una excepción: OC usa Nefrología proporcionalmente más. Ese dato es importante para interpretar el siguiente gráfico: si OC tiene más pacientes renales y aun así BC tiene mayor mortalidad en esa especialidad, la brecha no se puede explicar por el volumen de casos.
"""

# Gráfico 21: Top 10 Cirugías - BC vs OC
fig, axes = plt.subplots(1, 2, figsize=(15, 7))

for ax, casta in zip(axes, ["BC", "OC"]):
    subset = df_bc_oc_adultos[df_bc_oc_adultos["CASTE_NAME"] == casta]
    top10_cirugias = subset["SURGERY"].value_counts().head(10)
    total_casta_n = len(subset)
    pct = top10_cirugias / total_casta_n * 100

    bars = ax.barh(top10_cirugias.index[::-1], pct.values[::-1],
                   color=colores_casta[casta], edgecolor="white")

    for bar, val in zip(bars, pct.values[::-1]):
        ax.text(bar.get_width() + 0.2, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

    ax.set_title(f"{casta}  (n = {total_casta_n:,})", fontsize=11, fontweight="bold")
    ax.set_xlabel("% de casos")
    ax.set_xlim(0, pct.max() * 1.2)
    ax.tick_params(axis='y', labelsize=8)

plt.suptitle("Gráfico 21: Top 10 Cirugías más Frecuentes - BC vs OC", fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

"""En ambas castas: primer procedimiento hemodiálisis (13,6% BC vs 17,4% OC), segundo cirugía de fracturas (11,3% BC vs 12,2% OC).

A pesar de la diferencia en Nefrología que vimos recién, cuando bajamos al nivel del procedimiento puntual, BC y OC son casi idénticos: la hemodiálisis de mantenimiento primero, la cirugía de fracturas segundo. El tipo de procedimiento no explica las diferencias de resultado.
"""

# Gráfico 22: Mortalidad por Tipo de Hospital - BC vs OC
mort_hosp_casta = (df_bc_oc.groupby(["HOSP_TYPE", "CASTE_NAME"])["Mortality Y / N"]
                           .apply(lambda x: (x == "YES").mean() * 100)
                           .unstack(fill_value=0))

n_hosp_casta = (df_bc_oc.groupby(["HOSP_TYPE", "CASTE_NAME"]).size().unstack(fill_value=0))

etiquetas_hosp = {"G": "Gobierno (Público)", "C": "Corporativo (Privado)"}

fig, ax = plt.subplots(figsize=(9, 6))
x = range(len(mort_hosp_casta.index))
ancho = 0.35

for i, casta in enumerate(["BC", "OC"]):
    valores = mort_hosp_casta[casta]
    bars = ax.bar([xi + i * ancho for xi in x], valores,
                   width=ancho, label=casta, color=colores_casta[casta], edgecolor="white")
    for bar, val, hosp_idx in zip(bars, valores, mort_hosp_casta.index):
        n_val = n_hosp_casta.loc[hosp_idx, casta]
        ax.text(bar.get_x() + bar.get_width() / 2,
                val + 0.05,
                f"{val:.2f}%\n(n={n_val:,})",
                ha="center", va="bottom", fontsize=8)

ax.set_title("Gráfico 22: Tasa de Mortalidad por Tipo de Hospital - BC vs OC")
ax.set_xlabel("Tipo de hospital")
ax.set_ylabel("% mortalidad")
ax.set_xticks([xi + ancho / 2 for xi in x])
ax.set_xticklabels([etiquetas_hosp.get(i, i) for i in mort_hosp_casta.index])
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""En ambas castas, la mortalidad de pacientes del público casi duplica a los del privado.

Acá hay un dato que cambia la perspectiva: en los hospitales públicos, BC tiene más mortalidad que OC. Pero en los privados, el resultado se invierte ligeramente. Lo más importante no es esa pequeña inversión, sino que en ambas castas la mortalidad en el sector público casi duplica a la del privado. El tipo de hospital es un factor mucho más determinante que la casta en sí misma.
"""

# Gráfico 23: Distribución Geográfica - BC vs OC
top_distritos = df_bc_oc_adultos["DISTRICT_NAME"].value_counts().head(10).index.tolist()
df_distritos = df_bc_oc_adultos[df_bc_oc_adultos["DISTRICT_NAME"].isin(top_distritos)].copy()

dist_casta = (df_distritos.groupby(["DISTRICT_NAME", "CASTE_NAME"])
                          .size()
                          .unstack(fill_value=0))
dist_casta_pct = dist_casta.div(dist_casta.sum(axis=1), axis=0) * 100
dist_casta_pct = dist_casta_pct.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))
y = range(len(dist_casta_pct))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], dist_casta_pct["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], dist_casta_pct["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars in [bars_bc, bars_oc]:
    for bar in bars:
        val = bar.get_width()
        ax.text(val + 0.5, bar.get_y() + bar.get_height() / 2,
                f"{val:.1f}%", va="center", fontsize=8)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(dist_casta_pct.index, fontsize=9)
ax.set_title("Gráfico 23: Distribución por Distrito (Top 10) - BC vs OC")
ax.set_xlabel("% dentro de cada casta")
ax.set_xlim(0, dist_casta_pct.max().max() * 1.2)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""La composición de castas varía dramáticamente por distrito: de 93,9% BC en Srikakulam a 51,3% BC / 48,7% OC en Guntur.

Este gráfico es una advertencia metodológica: la composición de castas varía enormemente por zona. Donde hay 93,9% de BC es porque OC directamente casi no aparece en ese distrito. Si la calidad de los hospitales también varía por zona, parte de lo que atribuimos a la casta podría ser un efecto geográfico disfrazado.
"""

# Gráfico 24: Razón niñas/niños por distrito (top 10)
ninos_bc_oc = df_bc_oc[df_bc_oc["SEX_clean"].isin(["Male (Child)", "Female (Child)"])]
top10d = df_bc_oc["DISTRICT_NAME"].value_counts().head(10).index

d = ninos_bc_oc[ninos_bc_oc["DISTRICT_NAME"].isin(top10d)].groupby(
        ["DISTRICT_NAME","SEX_clean"]).size().unstack(fill_value=0)
d["ratio"] = d["Female (Child)"] / d["Male (Child)"]
d = d.sort_values("ratio")

fig, ax = plt.subplots(figsize=(9,6))
bars = ax.barh(d.index, d["ratio"], color="#8856a7", edgecolor="white")
ax.axvline(1.0, color="gray", linestyle="--", label="Paridad (1:1)")
for bar, val in zip(bars, d["ratio"]):
    ax.text(val+0.01, bar.get_y()+bar.get_height()/2, f"{val:.2f}", va="center", fontsize=8)
ax.set_xlabel("Niñas por cada niño tratado")
ax.set_title("Gráfico 24: Razón de género infantil por distrito (Top 10, BC+OC)")
ax.legend()
plt.tight_layout()
plt.show()

"""La razón niñas/niños varía de 0,54 (Krishna) a 0,71 (West Godavari): diferencia de 0,17 puntos.

Aquí la variación geográfica en la brecha de género es mucho mayor que la variación entre castas: 0,17 puntos de diferencia entre distritos, contra solo 0,03 entre BC y OC. El lugar donde vive una familia parece pesar más que su casta a la hora de definir si las niñas acceden al sistema.
"""

# Gráfico 25: Mortalidad por Especialidad - BC vs OC
top6_especialidades = df_bc_oc_adultos["CATEGORY_NAME"].value_counts().head(6).index.tolist()
df_top6_bc_oc = df_bc_oc_adultos[df_bc_oc_adultos["CATEGORY_NAME"].isin(top6_especialidades)].copy()

mort_esp_casta = (df_top6_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"])["Mortality Y / N"]
                                .apply(lambda x: (x == "YES").mean() * 100)
                                .unstack(fill_value=0))

n_esp_casta = (df_top6_bc_oc.groupby(["CATEGORY_NAME", "CASTE_NAME"]).size().unstack(fill_value=0))

mort_esp_casta = mort_esp_casta.sort_values("BC", ascending=True)

fig, ax = plt.subplots(figsize=(10, 7))
y = range(len(mort_esp_casta))
alto = 0.35

bars_bc = ax.barh([yi + alto for yi in y], mort_esp_casta["BC"],
                  height=alto, label="BC", color=colores_casta["BC"], edgecolor="white")
bars_oc = ax.barh([yi for yi in y], mort_esp_casta["OC"],
                  height=alto, label="OC", color=colores_casta["OC"], edgecolor="white")

for bars, casta in zip([bars_bc, bars_oc], ["BC", "OC"]):
    for bar, esp in zip(bars, mort_esp_casta.index):
        val = bar.get_width()
        n_val = n_esp_casta.loc[esp, casta]
        ax.text(val + 0.05, bar.get_y() + bar.get_height() / 2,
                f"{val:.2f}% (n={n_val:,})", va="center", fontsize=7)

ax.set_yticks([yi + alto / 2 for yi in y])
ax.set_yticklabels(mort_esp_casta.index, fontsize=9)
ax.set_title("Gráfico 25: Tasa de Mortalidad por Especialidad (Top 6) — BC vs OC")
ax.set_xlabel("% mortalidad")
ax.set_xlim(0, mort_esp_casta.max().max() * 1.4)
ax.legend(title="Casta")
plt.tight_layout()
plt.show()

"""Diferencia significativa SOLO en Nefrología. En las otras 5 especialidades: diferencias mínimas o nulas.

Al cruzar mortalidad por especialidad, la diferencia entre BC y OC prácticamente desaparece en cinco de las seis especialidades. Pero en Nefrología, BC registra 4,07% frente a 3,54% en OC, una diferencia de 0,53 puntos. Que la brecha se concentre justamente en Nefrología, la especialidad de la hemodiálisis crónica, sugiere que hay algo específico del tratamiento renal que perjudica más a los pacientes BC, tal vez acceso tardío al tratamiento o calidad diferencial de las unidades de diálisis.

# CONCLUSIONES

El análisis revela dos formas de desigualdad de naturaleza distinta:

* Desigualdad de acceso por género: las niñas llegan al sistema en menor número que los niños, y las que llegan lo hacen siendo más pequeñas, lo que sugiere que las familias las llevan solo ante cuadros urgentes. Esta pauta es transversal a ambas castas y es incluso ligeramente más marcada en OC, lo que indica que no es un problema de casta sino un patrón social más amplio.

* Desigualdad de resultado clínico, acotada y específica: dentro de Nefrología, BC presenta una mortalidad significativamente mayor que OC. En las otras cinco especialidades analizadas, la diferencia no es estadísticamente significativa.

Esto es metodológicamente más interesante que una afirmación genérica: la desigualdad no opera en todo el sistema por igual, sino en un punto específico del recorrido asistencial. Por qué ocurre exactamente ahí es una pregunta que este dataset no puede responder, ya que no contiene información sobre severidad clínica al ingreso ni calidad diferencial de prestadores.
"""
